export interface HoverHelpEntry {
  title: string;
  purpose?: string;
  usage?: string;
  effect?: string;
  summary?: string;
  whenToUse?: string;
  howToUse?: string;
  wiring?: string;
  bestPractices?: string;
  pitfalls?: string;
  example?: string;
}

function quickHelp(title: string, purpose: string, usage?: string, effect?: string): HoverHelpEntry {
  return { title, purpose, usage, effect };
}

const supplementalHoverHelpCatalog = {
  "asset.applyMask": quickHelp("应用重绘蒙版", "把当前绘制区域保存为本次局部重绘的独立蒙版。", "确认选区后点击；原图不会被破坏。"),
  "asset.aspectRatio": quickHelp("输出画幅", "切换常用宽高比或进入自定义尺寸。", "比例预设会同步更新宽度和高度。"),
  "asset.brushSize": quickHelp("蒙版笔刷大小", "调整蒙版画笔或橡皮的直径。", "细节边缘使用小笔刷，大面积区域使用大笔刷。"),
  "asset.cancelJob": quickHelp("取消生成任务", "取消当前队列任务并阻止迟到响应写回结果。", "已完成的候选图不会被删除。"),
  "asset.cancelRestore": quickHelp("取消恢复配方", "保留当前草稿，不应用历史配方。"),
  "asset.canvasRedo": quickHelp("重做画布操作", "重新应用刚刚撤销的蒙版编辑。", "也可使用 Ctrl/Cmd+Shift+Z。"),
  "asset.canvasUndo": quickHelp("撤销画布操作", "撤销最近一次蒙版编辑。", "也可使用 Ctrl/Cmd+Z。"),
  "asset.clearCache": quickHelp("清理未保存结果", "释放未入库候选图的本地缓存空间。", "任务和配方元数据会保留，图片会标记为缓存已过期。"),
  "asset.clearHistory": quickHelp("清除已完成历史", "移除已完成、失败、取消和中断的任务记录。", "正在排队或运行的任务不受影响。"),
  "asset.clearMask": quickHelp("清空蒙版", "移除当前画布上的全部蒙版笔迹。", "清空后仍可撤销。"),
  "asset.configureProvider": quickHelp("配置图像模型", "前往模型连接面板添加或启用图像生成模型。"),
  "asset.confirmRestore": quickHelp("确认恢复配方", "用历史任务的配方替换当前草稿。", "确认框会先列出发生变化的主要参数。"),
  "asset.count": quickHelp("生成数量", "设置本批需要的候选图数量。", "超过提供商单次上限时会自动拆分子请求。"),
  "asset.crop": quickHelp("裁为当前画幅", "在本地把来源图居中裁切到配方宽高。", "此操作不会调用生成模型，结果会作为本地处理候选记录。"),
  "asset.customPreset": quickHelp("我的配方预设", "载入项目中保存的素材类型、风格、画幅与提示词模板。"),
  "asset.customPresetName": quickHelp("预设名称", "为当前配方填写便于识别的自定义预设名称。"),
  "asset.displayName": quickHelp("素材显示名称", "设置生成结果进入素材库后的名称。", "批量保存时该名称会作为统一前缀。"),
  "asset.download": quickHelp("下载候选副本", "直接下载当前候选图，不写入项目素材库。"),
  "asset.eraseTransparency": quickHelp("透明擦除", "按当前蒙版在本地擦除图像像素并输出透明背景版本。", "原图保持不变。"),
  "asset.finishEditing": quickHelp("完成本地编辑", "退出蒙版、裁切与透明处理画布，返回结果舞台。"),
  "asset.height": quickHelp("精确高度", "设置期望输出高度（像素）。", "修改后画幅切换为自定义；比例型模型可能无法保证精确值。"),
  "asset.historyOperation": quickHelp("按操作筛选", "只显示指定生成操作的历史任务。"),
  "asset.historyProvider": quickHelp("按模型筛选", "只显示指定提供商或模型的历史任务。"),
  "asset.historySearch": quickHelp("搜索生成历史", "按提示词、模型名称或模型编号筛选历史。"),
  "asset.historyStatus": quickHelp("按状态筛选", "按完成、部分完成、失败、取消或中断筛选历史。"),
  "asset.historyTime": quickHelp("按时间筛选", "缩小历史记录的时间范围。"),
  "asset.historyType": quickHelp("按素材类型筛选", "只显示背景、立绘、头像、CG 或 UI 素材任务。"),
  "asset.makeVariation": quickHelp("制作变体", "继承当前结果与可复现参数，并使用新种子生成相近候选。", "仅在模型声明支持变体时可用。"),
  "asset.maskBrush": quickHelp("蒙版画笔", "绘制需要模型重新生成的区域。", "蒙版独立保存，不会覆盖来源图片。"),
  "asset.maskEraser": quickHelp("蒙版橡皮", "擦除已绘制的蒙版区域。"),
  "asset.mobilePane": quickHelp("切换工作台区域", "在窄窗口中切换创作设置、结果画布和任务面板。"),
  "asset.moveJobDown": quickHelp("任务下移", "把排队任务向后移动一个位置。", "运行中的任务不能排序。"),
  "asset.moveJobUp": quickHelp("任务上移", "把排队任务向前移动一个位置。", "运行中的任务不能排序。"),
  "asset.openCandidate": quickHelp("查看候选图", "把所选候选设为中央舞台的当前主结果。"),
  "asset.openHistoryJob": quickHelp("查看历史任务", "在舞台和本批结果中打开该历史任务的候选图。"),
  "asset.openJob": quickHelp("查看队列任务", "在舞台中查看该任务的阶段、进度和已有候选。"),
  "asset.operation": quickHelp("生成模式", "选择文生图、图生图、重绘、扩图、变体或放大。", "模型未声明支持的模式会提前禁用。"),
  "asset.outpaintInset": quickHelp("扩图边界", "设置来源图上、右、下、左需要扩展的像素范围。"),
  "asset.projectContext": quickHelp("项目上下文", "补充当前场景、角色、节点槽位或用途信息。", "内容会进入配方快照，帮助生成结果贴合项目。"),
  "asset.provider": quickHelp("图像模型", "选择本次任务使用的图像提供商和模型。", "切换后界面会按真实能力重新校验参数。"),
  "asset.railHistory": quickHelp("生成历史", "查看全部已结束的成功、失败、取消和中断任务。"),
  "asset.railQueue": quickHelp("任务队列", "查看排队、校验和运行中的任务及实时进度。"),
  "asset.railResults": quickHelp("本批结果", "查看当前任务的全部候选并进行多选保存。"),
  "asset.referenceMoveDown": quickHelp("参考图下移", "降低参考图在配方中的顺序。"),
  "asset.referenceMoveUp": quickHelp("参考图上移", "提高参考图在配方中的顺序。"),
  "asset.referenceNote": quickHelp("参考图备注", "记录参考图的身份、构图或使用说明。"),
  "asset.referenceRole": quickHelp("参考图用途", "指定参考图用于角色、构图、风格或色彩控制。", "不可用用途表示当前模型不支持。"),
  "asset.referenceWeight": quickHelp("参考图权重", "调整该参考图对生成结果的影响程度。"),
  "asset.removeReference": quickHelp("移除参考图", "从当前配方中移除这张参考图。", "不会删除素材库中的原始素材。"),
  "asset.removeSource": quickHelp("移除来源图片", "清除图生图、编辑、变体或放大的当前来源图。"),
  "asset.removeUnsupported": quickHelp("移除不支持参数", "清除当前模型不支持的操作、反向提示词、种子、参考图或蒙版。"),
  "asset.resizeComposer": quickHelp("调整创作栏宽度", "拖动改变左侧创作栏宽度。", "宽度会保存到项目工作台偏好。"),
  "asset.resizeRail": quickHelp("调整生产栏宽度", "拖动改变右侧任务与历史栏宽度。", "宽度会保存到项目工作台偏好。"),
  "asset.restoreRecipe": quickHelp("恢复历史配方", "准备从历史任务恢复完整参数。", "应用前会显示差异确认，不会静默覆盖草稿。"),
  "asset.retryJob": quickHelp("重试任务", "使用原配方重新加入生成队列。", "部分成功任务只重试失败的输出数量。"),
  "asset.reuseRecipe": quickHelp("复用全部参数", "把当前结果对应的完整配方载入创作栏。"),
  "asset.safetyLevel": quickHelp("安全级别", "选择本次生成使用的内容安全强度。", "提供商仍可能应用自己的安全策略。"),
  "asset.saveAndApply": quickHelp("保存并应用到槽位", "把结果写入素材库，并立即应用到打开工作台时指定的节点字段。"),
  "asset.saveAndOpenLibrary": quickHelp("保存并打开素材库", "保存全部选中结果后切换到素材库进行整理。"),
  "asset.saveCustomPreset": quickHelp("保存自定义预设", "把当前素材类型、风格、画幅与提示词模板保存到项目偏好。", "API Key、参考图和蒙版不会进入预设。"),
  "asset.saveFolder": quickHelp("保存文件夹", "选择生成素材进入素材库后的目标文件夹。"),
  "asset.saveFormat": quickHelp("保存格式", "选择 PNG、WebP 或 JPEG。", "需要透明通道时请选择 PNG 或 WebP。"),
  "asset.saveSelected": quickHelp("批量保存候选", "把本批勾选的候选图一起送入保存对话框。"),
  "asset.saveType": quickHelp("保存素材类型", "设置结果进入素材库后的分类。"),
  "asset.seed": quickHelp("随机种子", "固定支持种子的模型输出以便复现。", "留空会在每次任务中使用随机种子。"),
  "asset.selectCandidate": quickHelp("选择候选", "把候选加入或移出批量保存与比较集合。"),
  "asset.startInpaint": quickHelp("进入局部重绘", "以当前候选为来源，进入蒙版编辑并准备局部重绘配方。"),
  "asset.startOutpaint": quickHelp("进入扩图", "以当前候选为来源，设置四周扩展边界。"),
  "asset.startUpscale": quickHelp("进入 AI 放大", "以当前候选为来源，使用模型执行 2 倍或 4 倍放大。"),
  "asset.strength": quickHelp("重绘强度", "控制来源图片与新生成内容之间的保留程度。"),
  "asset.stylePreset": quickHelp("风格预设", "为提示词附加项目既有的视觉风格方向。"),
  "asset.switchProvider": quickHelp("切换图像模型", "前往模型连接面板选择支持当前操作的模型。"),
  "asset.toggleRail": quickHelp("切换生产栏", "在中等宽度窗口中打开或收起任务与历史抽屉。"),
  "asset.type": quickHelp("素材类型", "选择背景、立绘、头像、剧情 CG 或 UI 素材。", "会同步推荐画幅、尺寸和构图提示。"),
  "asset.undoRewrite": quickHelp("撤销提示词优化", "恢复优化前的主提示词。"),
  "asset.upscaleFactor": quickHelp("AI 放大倍数", "选择模型放大为原图的 2 倍或 4 倍。"),
  "asset.useRewriteWithNegative": quickHelp("应用完整优化建议", "同时采用优化后的正向提示词和反向提示词。", "仅在模型支持反向提示词时提交。"),
  "asset.viewCompare": quickHelp("A/B 对比", "并排比较当前主结果与下一张候选图。"),
  "asset.viewFocus": quickHelp("聚焦查看", "单独放大查看当前主结果。"),
  "asset.viewGrid": quickHelp("网格总览", "同时浏览当前任务的全部候选图。"),
  "asset.width": quickHelp("精确宽度", "设置期望输出宽度（像素）。", "修改后画幅切换为自定义；比例型模型可能无法保证精确值。"),
  "asset.zoomIn": quickHelp("放大画布", "放大本地编辑画布，最高 200%。"),
  "asset.zoomOut": quickHelp("缩小画布", "缩小本地编辑画布，最低 50%。"),
  "advanced.noticeDismiss": quickHelp("关闭面板提示", "收起当前高级工具面板顶部提示。", "阅读完配置提醒或跳转说明后点击。", "只隐藏提示条，不会改变项目数据。"),
  "app.reload": quickHelp("刷新编辑器", "在错误边界中重新加载 AgentVN 编辑器。", "页面进入异常状态且无法继续操作时使用。", "会刷新浏览器页面；未保存到项目状态的临时输入可能丢失。"),
  "asset.batch.copy": quickHelp("批量复制素材", "把选中的素材加入另一个素材库文件夹。", "先勾选素材，再选择目标文件夹执行复制。", "会更新素材库分类关系，不复制物理文件。"),
  "asset.batch.move": quickHelp("批量移动素材", "把选中的素材移动到指定素材库文件夹。", "整理大量素材时使用。", "会改变素材所在主文件夹，不影响命令中的 asset_id 引用。"),
  "asset.cancel": quickHelp("取消素材生成", "停止当前正在进行的素材生成请求。", "生成方向错误或等待过久时点击。", "已经完成并保存的素材不会被删除。"),
  "asset.cancelImport": quickHelp("取消导入", "关闭素材导入流程并放弃当前导入草稿。", "确认不想导入当前文件时使用。", "不会修改素材库。"),
  "asset.confirmImport": quickHelp("确认导入素材", "把当前选择的文件写入项目素材库。", "确认类型、授权说明和目标文件夹后点击。", "会新增或更新素材清单，导出时可被打包。"),
  "asset.delete": quickHelp("删除素材", "从项目素材库移除当前素材记录。", "删除前确认没有场景命令或 UI 设置仍在引用它。", "删除后相关引用可能在发布前检查中报缺失。"),
  "asset.editType": quickHelp("编辑素材类型", "修改当前素材在项目中的分类类型。", "素材导入类型识别错误时使用。", "会影响素材选择器筛选和导出清单分类。"),
  "asset.editType.save": quickHelp("保存素材类型", "保存当前素材类型修改。", "确认分类无误后点击。", "会更新素材清单，不改变素材文件本身。"),
  "asset.folder.card": quickHelp("素材文件夹", "查看素材文件夹的名称、数量和选中状态。", "点击或使用文件夹操作按钮管理素材分类。", "文件夹只影响编辑器整理方式，不改变导出的 asset_id。"),
  "asset.folder.create": quickHelp("新建素材文件夹", "创建一个用于整理素材的文件夹。", "按背景、角色、UI、音频等用途建立文件夹会更容易维护。", "只影响素材库组织方式。"),
  "asset.folder.delete": quickHelp("删除素材文件夹", "移除当前素材文件夹。", "删除前先确认文件夹中的素材是否需要移动。", "素材记录不会因为文件夹删除而自动从项目中删除。"),
  "asset.folder.name": quickHelp("文件夹名称", "编辑素材文件夹显示名称。", "使用清晰的用途名称，例如“主菜单 UI”或“第一章背景”。", "只影响编辑器内展示。"),
  "asset.folder.open": quickHelp("打开文件夹", "切换素材库到当前文件夹内容。", "需要查看或筛选该组素材时点击。", "不会修改素材数据。"),
  "asset.folder.toggle": quickHelp("展开文件夹", "展开或折叠素材库目录树中的子文件夹。", "浏览多层素材分类时使用。", "只改变目录显示，不移动素材。"),
  "asset.folder.rename": quickHelp("重命名文件夹", "进入当前文件夹名称编辑状态。", "分类命名不清楚时使用。", "只改文件夹名，不改素材引用。"),
  "asset.folder.save": quickHelp("保存文件夹", "保存新建或重命名的素材文件夹。", "填写名称后点击保存。", "会更新项目素材库结构。"),
  "asset.generate": quickHelp("生成素材", "按当前提示词和模型设置发起素材生成。", "写清用途、风格、尺寸和避讳内容后再生成。", "会消耗模型额度，结果需保存后才进入素材库。"),
  "asset.importFont": quickHelp("导入字体", "把字体文件加入项目素材库。", "需要让玩家客户端主题使用自定义字体时导入。", "导出时会随 UI skin 一起打包可用字体。"),
  "asset.importImage": quickHelp("导入图片", "把图片文件加入项目素材库。", "可用于背景、立绘、UI 底图或发布视觉资源。", "保存后可在素材选择器和客户端布局中引用。"),
  "asset.sidebar.close": quickHelp("关闭文件夹目录", "收起窄窗口中的素材文件夹目录。", "需要把更多空间留给素材缩略图时使用。", "不会改变当前文件夹或素材。"),
  "asset.sidebar.open": quickHelp("打开文件夹目录", "在窄窗口中打开素材文件夹目录。", "需要切换文件夹或拖放素材时使用。", "只改变目录显示。"),
  "asset.card.menu": quickHelp("素材操作", "打开当前素材的类型修改和删除操作。", "需要维护单个素材时使用。", "选择具体操作后才会修改素材。"),
  "asset.editType.cancel": quickHelp("取消修改类型", "关闭素材类型编辑浮层并放弃草稿。", "不想保存当前类型选择时使用。", "不会修改素材类型。"),
  "asset.license": quickHelp("素材授权说明", "记录素材来源、授权和使用备注。", "导入外部素材或生成素材时建议填写。", "用于后续整理和发布核查，不影响运行逻辑。"),
  "asset.negativePrompt": quickHelp("反向提示词", "描述生成素材时要避免的内容。", "写入不要出现的风格、瑕疵或元素。", "会随生成请求发送给支持反向提示的模型。"),
  "asset.prompt": quickHelp("素材提示词", "描述要生成或改写的素材内容。", "尽量包含用途、主体、风格、画幅和情绪。", "会作为模型生成或提示词改写的主要输入。"),
  "asset.reference": quickHelp("参考图", "为素材生成选择参考图片。", "需要保持角色、构图或风格一致时使用。", "会参与生成请求，具体效果取决于模型能力。"),
  "asset.rewrite": quickHelp("改写提示词", "让模型把当前素材提示词整理得更适合生成。", "提示词过短或不够稳定时使用。", "只生成改写建议，需确认后才替换原提示词。"),
  "asset.saveGenerated": quickHelp("保存生成素材", "把生成结果保存到项目素材库。", "确认图片可用、类型和授权备注无误后保存。", "保存后素材可被场景、发布视觉和客户端布局引用。"),
  "asset.saveGeneratedCancel": quickHelp("关闭保存弹窗", "关闭当前生成素材保存面板。", "暂时不想保存这张生成结果时点击。", "不会把当前生成结果写入项目素材库。"),
  "asset.select": quickHelp("选择素材", "把当前素材加入批量选择。", "用于批量移动、复制或管理素材。", "不会改变素材内容。"),
  "asset.useRewrite": quickHelp("使用改写结果", "把改写后的提示词应用回当前输入框。", "确认改写内容符合创作意图后点击。", "会替换提示词文本，不会自动发起生成。"),
  "canvas.resizer": quickHelp("调整画布区域", "拖动改变编辑画布和侧边栏的空间比例。", "当检查器或画布空间不够时使用。", "尺寸只影响当前编辑器布局。"),
  "command.animation.blocking": quickHelp("等待动画结束", "控制动画播放时是否阻塞后续命令。", "关键演出需要播完再继续时开启。", "会影响运行时命令推进节奏。"),
  "command.animation.params": quickHelp("动画参数 JSON", "编辑演出动画的底层参数。", "只有模板控件无法表达需求时再手写。", "格式错误会导致运行端忽略或回退动画。"),
  "command.animation.target": quickHelp("动画目标", "选择演出动画作用到哪个运行端对象。", "例如屏幕、背景、对白框或指定立绘。", "导出后决定 GameCLI 应用动画的目标元素。"),
  "command.background.backgroundFit": quickHelp("背景显示模式", "控制剧情背景命令在舞台中如何显示背景图。", "强制铺满会拉伸到舞台宽高；完整显示保留整张图；裁切铺满保持比例并填满舞台。", "导出后写入 BackgroundCommand.background_fit，旧命令缺省按强制铺满处理。"),
  "command.showImage.imageId": quickHelp("展示图片素材", "选择剧情中需要聚焦展示的关键物品、线索、照片或信件图片。", "支持背景、立绘、头像和 UI 图片素材。", "运行时会阻塞剧情并覆盖整个播放画面，玩家关闭后才继续。"),
  "command.showImage.displayName": quickHelp("展示图片名称", "填写作者侧和缺失素材提示中使用的可读名称。", "使用简短物品名或线索名，例如“沾血的钥匙”。", "不改变素材 ID，只改善编辑和异常提示。"),
  "command.showImage.fit": quickHelp("展示图片填充", "控制聚焦图片在可用区域内的缩放方式。", "完整显示适合物品和信件；覆盖裁切适合照片；拉伸填满仅用于允许变形的素材。", "导出为 show_image.image_fit。"),
  "command.showImage.imageFit": quickHelp("展示图片填充", "控制聚焦图片在可用区域内的缩放方式。", "完整显示适合物品和信件；覆盖裁切适合照片；拉伸填满仅用于允许变形的素材。", "导出为 show_image.image_fit。"),
  "command.showImage.caption": quickHelp("图片说明", "在聚焦图片下方显示一段可选剧情说明。", "适合补充刻字、编号或角色观察到的细节。", "说明会随覆盖层显示，并与图片一起淡出。"),
  "command.showImage.alt": quickHelp("无障碍描述", "为无法查看图片的玩家描述关键视觉信息。", "准确写出推进剧情所需的物品外观和文字内容。", "运行端会作为图片替代文本使用。"),
  "command.showImage.backdropOpacity": quickHelp("背景暗度", "设置图片展示时底层剧情画面的压暗程度。", "范围为 0 到 0.9，默认 0.62。", "运行端会钳制范围并应用到全屏遮罩。"),
  "command.showImage.backdropBlur": quickHelp("背景模糊", "设置图片展示时底层剧情画面的模糊强度。", "范围为 0 到 24 像素，默认 12。", "运行端会钳制范围并应用 backdrop-filter。"),
  "command.bgm.fadeMs": quickHelp("音乐淡入淡出", "设置背景音乐切换或停止时的渐变时长。", "希望音乐更自然过渡时填写毫秒数。", "会写入 BGM 命令并影响运行时音频过渡。"),
  "command.bgm.volume": quickHelp("音乐音量", "设置当前 BGM 命令的播放音量。", "使用 0 到 1 的范围控制相对音量。", "运行端会与玩家总音量设置叠加。"),
  "command.camera.blocking": quickHelp("等待镜头结束", "控制镜头动画是否阻塞后续命令。", "镜头移动是关键演出节拍时开启。", "会影响剧情推进等待时长。"),
  "command.camera.params": quickHelp("镜头参数 JSON", "编辑镜头移动、缩放或震动的底层参数。", "高级镜头效果可在这里补充。", "格式错误会影响镜头命令执行。"),
  "command.choice.add": quickHelp("添加选项", "为当前选择命令追加一个玩家选项。", "需要增加分支或回应按钮时点击。", "会新增 choice 项，后续需设置文本和目标场景。"),
  "command.choice.choiceId": quickHelp("选项 ID", "设置选项的稳定编号。", "保持短小且语义清楚，例如 choice_truth。", "导出分支和存档兼容会依赖该编号。"),
  "command.choice.targetSceneId": quickHelp("目标场景", "设置玩家选择后跳转到的场景 ID。", "建议从这个选项的画布手柄连到目标场景，连线后会自动填入；也可以手填兼容旧数据。", "运行端会按此 ID 进入下一场景。"),
  "command.choice.text": quickHelp("选项文案", "设置作者侧显示名和玩家实际看到的选项文案。", "写成玩家意图，而不是路线编号；输入内容会同步写入 choice_display_name 和 text。", "会直接显示在 GameCLI 选择界面，也用于编辑器中辨认分支。"),
  "command.delete": quickHelp("删除命令", "移除当前事件命令或选项。", "确认该命令不再需要时点击。", "删除会立即改变当前场景事件列表。"),
  "command.dialog.characterId": quickHelp("对白角色", "设置当前对白所属角色。", "选择稳定角色 ID 以便立绘、默认对白样式和语音关联。", "导出后会写入 DialogCommand.character_id。"),
  "command.dialog.emotion": quickHelp("角色情绪", "记录当前对白使用的情绪状态。", "用于区分立绘表情、语音或后续检索。", "运行端可根据项目资源显示对应表现。"),
  "command.dialog.portrait.applyAll": quickHelp("批量应用头像", "把当前头像设置应用到同角色后续对白。", "确定角色头像需要统一时使用。", "不会覆盖已经手动改成其他头像的特殊对白。"),
  "command.dialog.text": quickHelp("对白文本", "编辑角色说出的文本内容。", "保持每条对白节奏清楚，避免塞入过长段落。", "会直接进入运行剧本并显示给玩家。"),
  "command.narration.text": quickHelp("旁白文本", "编辑没有角色名的叙述文本。", "用于环境、心理活动或转场说明。", "会作为旁白命令显示在运行端。"),
  "command.sfx.volume": quickHelp("音效音量", "设置当前音效命令的相对音量。", "根据音效强弱微调，避免压过对白。", "运行端会与玩家音效总音量叠加。"),
  "command.sprite.characterId": quickHelp("立绘角色", "设置当前立绘命令控制的角色。", "选择后可控制该角色立绘显示、隐藏和动效。", "导出后会定位到对应 sprite 目标。"),
  "command.sprite.visible": quickHelp("立绘可见性", "控制当前角色立绘显示或隐藏。", "角色入场、退场或临时消失时切换。", "运行端会按该状态更新立绘。"),
  "command.state.key": quickHelp("状态变量名", "设置要写入的运行时变量名称。", "使用清晰稳定的英文或拼音 ID。", "后续条件判断会读取该变量。"),
  "command.state.value": quickHelp("状态变量值", "设置变量写入或计算使用的值。", "根据变量类型填写布尔、数字或文本。", "会影响后续条件分支和存档状态。"),
  "command.state.operation": quickHelp("状态操作", "选择如何修改运行时变量。", "循环初始化推荐使用 set_if_unset，普通赋值用 set，计数用 add/subtract。", "set_if_unset 只在变量不存在时写入，适合循环节点反复回跳时避免重置计数。"),
  "command.jump.targetSceneId": quickHelp("跳转目标场景", "设置无条件 jump 事件要进入的目标场景。", "用于战斗回合、搜寻循环、巡逻和快速转场；也可以通过节点默认出口连线维护。", "导出前会校验目标存在并可导出，运行时会直接跳到目标 scene_id。"),
  "node.loop": quickHelp("重复剧情节点", "让一段剧情执行多次，例如搜索 3 次、进行 5 个战斗回合，或一直尝试到找到钥匙。", "先选择“重复 3 次”等常用方案，再连接两条路线：左边去需要重复的第一个场景，右边去重复完成后的场景。最后把需要重复的最后一个场景连回本节点。", "两条路线都连接好后，系统会自动记录次数并决定是再做一次还是继续后面的剧情。"),
  "node.loop.condition": quickHelp("什么时候再做一次", "系统每次回到本节点都会检查一句规则；满足时再执行一轮，不满足时结束重复。", "例如“搜索次数小于等于 3”表示还没超过 3 次时继续搜索。只需固定次数时，优先使用上方的常用方案。", "这条规则决定剧情走左侧“再做一次”还是右侧“重复完成”路线。"),
  "field.loop.variableKey": quickHelp("次数记录名称", "这是系统用来保存“已经做了几次”的记录名称。", "建议使用简短英文和下划线，例如 search_count（搜索次数）或 battle_turn（战斗回合）；同一项目中不要重名。", "返回本节点时会继续使用已有记录，不会从头清零。"),
  "field.loop.initialValue": quickHelp("开始前记作几次", "设置第一次执行前，系统认为已经完成了几次。", "通常填 0，表示一轮都还没有完成。只有接续已有进度时才需要修改。", "系统会先读取这个数字，再按“每完成一轮增加多少”更新记录。"),
  "field.loop.step": quickHelp("每完成一轮增加多少", "每次回到本节点时，系统会把次数记录增加或减少这里填写的数字。", "普通计数填 1；倒数时可以填 -1；不要填 0。", "填 0 会让次数记录一直不变，如果继续规则始终满足，剧情可能无法结束。"),
  "command.wait.durationMs": quickHelp("等待时长", "插入一段毫秒级等待。", "用于停顿、节奏控制或等待演出余韵。", "运行端会暂停推进指定时间。"),
  "field.authorGoal": quickHelp("作者目标", "描述希望 AI 接下来补写的剧情方向。", "写清角色动机、冲突、氛围和需要避免的内容。", "会作为辅助生成当前场景的核心提示。"),
  "field.autoApplyMemory": quickHelp("自动应用记忆", "控制生成时是否自动把匹配记忆写入上下文。", "需要保持角色设定和世界观一致时开启。", "会影响模型生成输入，不直接改剧情。"),
  "field.autoExtractMemory": quickHelp("自动提取记忆", "控制生成后是否从内容中提取可复用记忆。", "适合长期连载项目维护设定。", "会更新项目记忆库。"),
  "field.chapter": quickHelp("章节编号", "标记当前场景所属章节。", "用于排序、检索和导出组织。", "不会直接影响运行逻辑。"),
  "field.conditionExpression": quickHelp("条件表达式", "编辑条件节点或命令使用的判断表达式。", "优先使用可视化条件构建器，复杂情况再手写。", "表达式决定真假分支走向。"),
  "field.conditionKey": quickHelp("条件变量", "选择或填写要判断的运行时变量。", "变量名应与修饰节点写入的 key 保持一致。", "运行端会读取该变量判断分支。"),
  "field.conditionValue": quickHelp("比较值", "设置条件判断右侧的比较值。", "根据变量类型填写数字、布尔或文本。", "会影响条件真假结果。"),
  "field.endingId": quickHelp("结局 ID", "设置结局节点的稳定编号。", "保持唯一且语义明确。", "运行端存档和结局记录会引用它。"),
  "field.endingTitle": quickHelp("结局标题", "设置玩家看到或导出记录中的结局名称。", "用简短有辨识度的标题。", "会进入运行剧本结局数据。"),
  "field.falseLabel": quickHelp("否分支标签", "设置条件不满足时的出口名称。", "用剧情语义命名，例如“未取得钥匙”。", "便于画布和导出分支理解。"),
  "field.generationOutline": quickHelp("生成大纲", "描述当前节点希望生成或补全的内容。", "写清剧情动作、角色关系和演出节奏。", "会作为 AI 丰富当前节点的主要输入。"),
  "field.scene_display_name": quickHelp("场景中文代称", "设置便于作者阅读的场景显示名。", "可使用中文短标题，不影响稳定 ID。", "主要用于编辑器展示和检索。"),
  "field.scene_id": quickHelp("场景 ID", "当前场景的稳定机器编号。", "通常由系统生成，不建议随意修改。", "导出、跳转和连线会依赖它。"),
  "field.summary": quickHelp("场景摘要", "概括当前场景发生了什么。", "写成可检索的短说明。", "会帮助 AI 和记忆系统理解上下文。"),
  "field.tags": quickHelp("标签", "为当前场景添加检索标签。", "用逗号分隔人物、地点、章节或状态。", "只影响编辑器组织和检索。"),
  "field.title": quickHelp("场景标题", "设置当前节点在画布和检查器中的标题。", "标题应概括场景戏剧动作。", "会影响编辑器展示和导出场景标题。"),
  "field.trueLabel": quickHelp("是分支标签", "设置条件满足时的出口名称。", "用剧情语义命名，例如“信任足够”。", "便于画布和导出分支理解。"),
  "home.deleteDialogCancel": quickHelp("取消删除", "关闭最近项目删除确认框。", "不确定是否删除时点击。", "不会移除任何最近项目记录。"),
  "home.deleteDialogClose": quickHelp("关闭删除确认", "关闭最近项目删除弹窗。", "阅读完确认提示后可关闭。", "不会删除项目。"),
  "home.deleteDialogConfirm": quickHelp("确认删除记录", "从最近项目列表移除该记录。", "仅当确定不再需要这个入口时点击。", "通常只移除最近记录，不删除工程文件本体。"),
  "home.deleteRecentProject": quickHelp("删除最近项目记录", "打开最近项目移除确认。", "清理无效或不再使用的项目入口时使用。", "不会立即删除，需再次确认。"),
  "home.importProject": quickHelp("导入项目", "从本地选择 AgentVN 项目文件并作为当前工程打开。", "迁移工程或打开外部项目时使用；若想把另一份工程作为独立线路加入当前画布，请在编辑器顶部工具栏使用导入工程。", "主页导入会载入该工程并进入编辑器，不会把它合并到已有节点流。"),
  "home.openDraft": quickHelp("继续上次编辑", "打开最近一次自动保存的项目草稿。", "想快速回到上次工作状态时点击。", "会载入本机保存的编辑器草稿。"),
  "home.recentProject": quickHelp("最近项目", "打开最近编辑过的项目。", "从列表中选择目标工程继续编辑。", "会载入该项目记录对应的数据。"),
  "inspector.deleteNode": quickHelp("删除节点", "删除当前选中的画布节点。", "确认该节点和相关连线不再需要时使用。", "会改变剧情蓝图结构。"),
  "inspector.duplicateNode": quickHelp("复制节点", "复制当前选中的画布节点。", "需要复用类似场景结构时使用。", "会创建一个新的节点副本。"),
  "layout.align": quickHelp("对齐组件", "把选中的客户端布局组件按指定方向对齐。", "用于快速整理 UI 控件位置。", "会修改当前断点下组件坐标。"),
  "layout.applyPreset": quickHelp("应用布局预设", "把当前页面或组件恢复到预设布局。", "布局混乱或想快速起步时使用。", "会修改当前布局草稿，保存后才导出。"),
  "layout.color": quickHelp("布局颜色", "设置当前布局组件的背景、文字或边框颜色。", "用于局部覆盖客户端主题颜色。", "会写入组件 style 并覆盖继承 token。"),
  "layout.component": quickHelp("布局组件", "选择或定位客户端布局中的组件。", "需要编辑某个 UI 控件的位置、尺寸或样式时使用。", "选中后右侧参数会切换到该组件。"),
  "layout.desktop": quickHelp("桌面布局", "切换到桌面 16:9 布局断点。", "调整电脑窗口下玩家客户端 UI 时使用。", "会编辑组件 rect。"),
  "layout.fontWeight": quickHelp("字体粗细", "设置当前布局组件文字字重。", "标题、按钮可适当加粗，正文保持可读。", "会写入组件 style.fontWeight。"),
  "layout.healthDetails": quickHelp("布局体检详情", "展开布局结构错误和可读性警告。", "保存或导出前检查问题时使用。", "只展开诊断，不自动修改布局。"),
  "layout.label": quickHelp("组件标签", "编辑布局组件在设计器中的显示名称。", "用于更容易识别自定义组件用途。", "主要影响编辑器展示。"),
  "layout.layer": quickHelp("图层顺序", "调整当前组件在客户端 UI 中的前后层级。", "当控件互相遮挡时使用。", "会修改 zIndex 或组件顺序。"),
  "layout.lock": quickHelp("锁定组件", "锁定或解锁当前布局组件。", "防止误拖动重要控件时开启。", "锁定后不可直接移动或编辑部分参数。"),
  "layout.mobile": quickHelp("手机横屏布局", "切换到手机横屏 16:9 布局断点。", "调整横屏移动端玩家 UI 时使用。", "会编辑组件 mobileRect。"),
  "layout.rect": quickHelp("位置与尺寸", "调整当前组件的百分比位置和宽高。", "使用滑杆或数字框微调。", "保存后 GameCLI 会按窗口尺寸换算实际像素。"),
  "layout.redo": quickHelp("重做布局", "恢复刚刚撤销的布局操作。", "误撤销后点击。", "只影响当前布局草稿。"),
  "layout.restoreAll": quickHelp("恢复全部布局", "把所有页面布局恢复为默认值。", "布局整体失控时使用。", "会重置当前主题布局草稿中的组件位置。"),
  "layout.restoreCurrent": quickHelp("恢复当前组件", "把当前选中组件恢复为默认布局。", "某个控件调整失败时使用。", "只影响当前组件。"),
  "layout.save": quickHelp("保存布局", "把当前客户端布局写入项目。", "确认体检没有阻断错误后点击。", "保存后会随卡带导出到 ui/layout.json。"),
  "layout.screen": quickHelp("布局页面", "切换标题页、播放页、设置页等客户端页面。", "选择要编辑的玩家端界面。", "只切换设计器视图。"),
  "layout.showGrid": quickHelp("显示网格", "显示或隐藏布局画布网格。", "需要精细对齐时开启。", "只影响设计器显示。"),
  "layout.showNames": quickHelp("显示名称", "显示或隐藏组件名称标签。", "组件较多时用于识别控件。", "只影响设计器显示。"),
  "layout.showSafeArea": quickHelp("显示安全区", "显示玩家端推荐安全区域。", "避免控件贴边或被设备裁切时开启。", "只影响设计器辅助线。"),
  "layout.snapCenter": quickHelp("吸附中心线", "拖动组件时吸附画布中心线。", "需要居中对齐时开启。", "只影响拖拽辅助行为。"),
  "layout.snapEdges": quickHelp("吸附边缘", "拖动组件时吸附其他控件边缘。", "整理多控件间距时使用。", "只影响拖拽辅助行为。"),
  "layout.snapGrid": quickHelp("吸附网格", "拖动组件时吸附到网格单位。", "需要规整布局时开启。", "只影响拖拽辅助行为。"),
  "layout.snapSafe": quickHelp("吸附安全区", "拖动组件时吸附到安全区边界。", "防止控件过度贴边时使用。", "只影响拖拽辅助行为。"),
  "layout.undo": quickHelp("撤销布局", "撤销上一步布局修改。", "误调位置、尺寸或样式时使用。", "只影响当前布局草稿。"),
  "layout.visibility": quickHelp("显示组件", "切换当前布局组件是否可见。", "需要隐藏某个默认控件时使用。", "保存后运行端会按 visible 渲染。"),
  "layout.zIndex": quickHelp("图层值", "设置组件前后层级数值。", "数值越大越靠前。", "会写入组件 zIndex。"),
  "layout.zoom": quickHelp("设计器缩放", "调整客户端布局画布预览缩放比例。", "需要整体查看或精细调整时切换。", "只影响编辑器预览。"),
  "novel.branchSuggestions": quickHelp("分支建议", "查看小说导入过程中模型建议的分支方向。", "复核自动改编结构时使用。", "不会自动写入画布。"),
  "novel.chapterTitle": quickHelp("章节标题", "编辑导入小说识别出的章节标题。", "标题错误或需要统一格式时修改。", "会影响后续场景分组和蓝图命名。"),
  "novel.characterDescription": quickHelp("角色描述", "编辑导入识别出的角色设定说明。", "补充身份、性格和剧情作用。", "会帮助后续蓝图生成理解角色。"),
  "novel.characterId": quickHelp("角色 ID", "设置导入角色的稳定编号。", "使用简短唯一 ID，避免后续频繁修改。", "会影响对白和立绘引用。"),
  "novel.characterName": quickHelp("角色名称", "编辑玩家和作者看到的角色名。", "保持与原文称呼一致。", "会写入角色清单和对白显示。"),
  "novel.clean": quickHelp("重新清洗文本", "重新规范化导入小说文本。", "原文有异常空格、乱码或排版问题时使用。", "会更新清洗后的文本草稿。"),
  "novel.continueQualityRisk": quickHelp("继续有风险导入", "在质量检查存在风险时继续流程。", "确认问题可接受或准备后续人工修正时点击。", "会跳过当前质量阻断。"),
  "novel.extractCharacters": quickHelp("识别角色", "从已切分文本中提取角色候选。", "场景切分后执行，便于后续对白归属。", "会生成可编辑角色列表。"),
  "novel.importFile": quickHelp("导入小说文件", "选择本地小说文本文件。", "支持按当前导入流程读取和清洗。", "不会立即写入画布。"),
  "novel.normalizedText": quickHelp("清洗后文本", "查看或编辑规范化后的小说文本。", "用于修正导入前的文本结构。", "后续拆章拆场景会使用这里的内容。"),
  "novel.normalizedTextToggle": quickHelp("显示清洗文本", "展开或收起清洗后的小说文本。", "需要人工检查导入质量时使用。", "只影响面板显示。"),
  "novel.rawText": quickHelp("原始文本", "查看导入文件的原始内容。", "用于对比清洗前后差异。", "只读，不直接参与编辑。"),
  "novel.retryQuality": quickHelp("重试质量检查", "重新运行小说导入质量检查。", "修正文本或参数后使用。", "会刷新质量报告。"),
  "novel.sceneTitle": quickHelp("场景标题", "编辑导入候选场景标题。", "标题应概括该段剧情动作。", "会影响生成节点名称。"),
  "novel.splitChapters": quickHelp("切分章节", "根据文本结构拆分小说章节。", "清洗文本后执行。", "会生成章节候选列表。"),
  "novel.splitScenes": quickHelp("切分场景", "把章节继续拆分成可改编场景。", "章节确认后执行。", "会生成场景候选列表。"),
  "package.androidEnvCheck": quickHelp("检查 Android 环境", "检测本机 Android 打包依赖是否可用。", "准备构建 APK 前先运行。", "只做检查，不安装依赖。"),
  "package.androidEnvInstall": quickHelp("修复 Android 环境", "尝试安装或修复 Android 打包依赖。", "环境检查失败且你希望自动处理时使用。", "会调用本机工具链，可能需要等待。"),
  "package.windowsEnvCheck": quickHelp("检查 Windows 环境", "检测本机 Windows EXE/MSI 打包依赖是否可用。", "准备构建 Windows 独立包前先运行。", "只做检查，不安装依赖。"),
  "package.windowsEnvInstall": quickHelp("修复 Windows 环境", "尝试安装或修复 Node.js、Rust、MSVC Build Tools 等 Windows 打包依赖。", "环境检查失败且你希望自动处理时使用。", "会调用 winget/本机工具链，可能需要等待或管理员权限。"),
  "package.author": quickHelp("发布作者", "填写卡带发布信息中的作者或团队名。", "发布前必须填写清楚。", "会进入 manifest 元数据。"),
  "package.close": quickHelp("关闭发布面板", "关闭发布与打包弹层。", "暂时不导出时点击。", "不会清空已填写的发布草稿。"),
  "package.confirmWarnings": quickHelp("确认风险", "确认已阅读发布前警告并仍要继续。", "仅在你理解阻断或警告影响时勾选。", "会影响导出按钮是否可用。"),
  "package.description": quickHelp("游戏简介", "填写卡带描述文本。", "用于发布页和 manifest 说明。", "不会影响剧情内容。"),
  "package.gameId": quickHelp("游戏编号", "设置卡带的稳定 game_id。", "使用英文、数字或下划线，发布后尽量不要改。", "存档兼容和发布识别会依赖它。"),
  "package.includeGallery": quickHelp("包含画廊清单", "控制导出时是否附带 gallery.json。", "作品有画廊或 CG 回看时开启。", "会增加可选运行时数据。"),
  "package.includeMetadata": quickHelp("包含发布信息", "控制导出时是否附带发布元数据。", "需要记录制作信息、许可或版本说明时开启。", "会写入 metadata 文件。"),
  "package.language": quickHelp("发布语言", "设置卡带默认语言标签。", "例如 zh-CN、en-US。", "会进入 manifest language 字段。"),
  "package.title": quickHelp("游戏标题", "填写玩家看到的作品标题。", "使用正式发布名称。", "会进入 manifest 和玩家端展示。"),
  "package.version": quickHelp("版本号", "设置当前发布版本。", "建议使用 0.1.0 这类语义版本。", "会进入 manifest 并帮助区分发布包。"),
  "preview.choice": quickHelp("预览选项", "在内置预览中选择一个分支。", "测试当前剧情分支时点击。", "只影响预览状态。"),
  "preview.closePanel": quickHelp("关闭预览", "收起内置剧情预览面板。", "不需要继续检查时点击。", "不会改变项目数据。"),
  "preview.openPanel": quickHelp("打开预览", "打开内置剧情预览面板。", "快速检查当前节点播放效果时使用。", "只运行编辑器内预览。"),
  "provider.addConnection": quickHelp("添加连接", "新增一个模型供应商连接。", "需要接入 OpenAI 兼容服务或本地模型时使用。", "只保存编辑器配置，不导出到玩家端。"),
  "provider.addManualModel": quickHelp("手动添加模型", "在当前连接下手动添加一个模型条目。", "自动探测不到模型时使用。", "会写入编辑器模型配置。"),
  "provider.apiToken": quickHelp("API 密钥（API Token）", "填写当前模型服务的访问密钥。", "只在本机编辑器中使用。", "不会写入导出的卡带。"),
  "provider.baseUrl": quickHelp("接口地址", "设置模型服务的基础 URL。", "使用 OpenAI 兼容接口时填写。", "会影响助手、导入和素材生成请求。"),
  "provider.connectionName": quickHelp("连接名称", "给模型连接起一个便于识别的名字。", "可按供应商或用途命名。", "只影响编辑器展示。"),
  "provider.deleteConnection": quickHelp("删除连接", "移除当前模型供应商连接。", "确认不再使用该连接时点击。", "会删除该连接下的本地配置。"),
  "provider.deleteModel": quickHelp("删除模型", "从当前连接中移除模型条目。", "模型不可用或不再需要时使用。", "不会删除远端模型。"),
  "provider.detectModels": quickHelp("探测模型", "向当前连接请求可用模型列表。", "配置好地址和 Token 后点击。", "会更新本地模型列表。"),
  "provider.displayName": quickHelp("模型显示名", "设置模型在编辑器中显示的名称。", "用易懂名称区分用途。", "只影响编辑器展示。"),
  "provider.enableConnection": quickHelp("启用连接", "控制当前模型连接是否参与可用模型选择。", "临时停用某个供应商时关闭。", "不会删除配置。"),
  "provider.enableModel": quickHelp("启用模型", "控制当前模型是否可被功能选择。", "模型不稳定或不想使用时关闭。", "不会删除模型条目。"),
  "provider.maxTokens": quickHelp("最大输出长度", "设置文本模型单次回复的 token 上限。", "长文生成需要更高值，短问答可降低。", "会影响模型请求参数。"),
  "provider.modelId": quickHelp("模型 ID", "填写服务端识别的真实模型编号。", "必须与供应商接口返回或文档一致。", "会用于实际 API 请求。"),
  "provider.save": quickHelp("保存模型配置", "保存当前连接和模型设置。", "修改地址、Token 或参数后点击。", "只保存到编辑器本机/项目配置。"),
  "provider.selectConnection": quickHelp("选择连接", "切换正在编辑的模型连接。", "多个供应商之间切换时使用。", "只影响当前设置面板。"),
  "provider.temperature": quickHelp("创造性", "设置文本模型回复的随机性。", "需要稳定结构时降低，需要发散创作时提高。", "会写入模型请求参数。"),
  "provider.thinkingMode": quickHelp("思考模式", "设置支持推理模型的思考/推理强度。", "需要复杂规划时启用更高模式。", "取决于模型是否支持。"),
  "provider.topP": quickHelp("核采样范围（Top P）", "设置文本模型采样范围。", "通常保持默认；需要更稳定时降低。", "会影响模型输出分布。"),
  "scene.generateNext": quickHelp("辅助生成后续", "让 AI 根据当前场景继续生成后续内容。", "先填写清楚场景摘要和作者目标。", "会向当前节点或后续节点写入生成结果。"),
  "settings.importFont": quickHelp("导入主题字体", "为客户端主题导入可用字体文件。", "需要玩家端使用自定义字体时点击。", "字体会进入项目素材并可随 UI skin 导出。"),
  "sketch.brush": quickHelp("画笔", "在草图板中使用画笔绘制。", "绘制参考构图或遮罩时使用。", "只影响当前草图。"),
  "sketch.clear": quickHelp("清空草图", "清除草图板内容。", "想重新绘制时使用。", "会删除当前草图画面。"),
  "sketch.eraser": quickHelp("橡皮擦", "在草图板中擦除笔迹。", "修正局部草图时使用。", "只影响当前草图。"),
  "sketch.export": quickHelp("导出草图", "把草图导出为图片或参考素材。", "需要作为生成参考时使用。", "导出后可用于素材流程。"),
  "start.loadingAnimation.addFrame": quickHelp("添加开屏帧", "把选择的图片加入开屏图片序列。", "制作多帧加载动画时使用。", "会更新入口节点 loading_animation。"),
  "toolbar.backendHealth": quickHelp("检查后端", "检测编辑器后端服务是否在线。", "模型、预览或导出异常时先检查。", "只发起健康检查，不修改项目。"),
  "toolbar.exportScript": quickHelp("导出运行剧本", "导出纯运行剧本 JSON。", "需要调试或外部查看 script 数据时使用。", "不会生成完整 .vncart。"),
  "toolbar.home": quickHelp("返回项目主页", "回到 AgentVN 项目主页。", "切换项目或查看最近项目时使用。", "当前项目会先保存到编辑器状态。"),
  "toolbar.importProject": quickHelp("导入独立线路", "把另一个 AgentVN 工程的节点作为一条独立线路加入当前画布。", "适合把完全不同的路线、支线或备份片段放进当前节点编辑器对照整理。", "会重命名导入节点与 scene_id、保留内部连线，并放到画布右侧；不会自动拼接到当前入口或现有节点流，需要手动连线后才会进入玩家可达流程。"),
  "toolbar.exportCartridge": quickHelp("发布与打包", "打开卡带导出和独立软件包打包面板。", "准备发布 .vncart、Windows 包或 Android APK 时使用。", "会执行发布前检查并按选择导出。"),
  "toolbar.saveProject": quickHelp("保存项目", "把当前工程保存为 AgentVN 项目文件。", "阶段性备份或迁移工程时使用。", "会下载或写出项目文件。"),
  "toolbar.theme": quickHelp("编辑器明暗主题", "切换编辑器自身的浅色或深色外观。", "根据工作环境切换。", "只影响编辑器，不影响玩家客户端主题。"),
} as const satisfies Record<string, HoverHelpEntry>;

export const hoverHelpCatalog = {
  ...supplementalHoverHelpCatalog,
  "scene.enrichCurrent": {
    title: "丰富当前节点",
    purpose: "根据当前填写的生成大纲，把内容直接写回选中的场景卡片。",
    usage: "先在“下一步生成大纲”里写清楚要补足的剧情、角色表现和演出方向，再点击这里生成。",
    effect: "会保留当前 scene_id 和章节编号，只更新当前节点的标题、摘要和事件命令，不会创建新的后续节点。",
  },
  "layout.anchor": {
    title: "布局锚点",
    purpose: "决定组件的 x/y 坐标从哪个基准点解释，例如左上角、中心或右上角。",
    usage: "需要控件贴边或围绕中心缩放时选择对应锚点；例如快捷菜单常用右上角，选项列表常用中心。",
    effect: "会写入 ui/layout.json，GameCLI 在不同窗口尺寸下会按该锚点重新换算控件位置。",
  },
  "layout.backgroundFit": {
    title: "背景显示模式",
    purpose: "控制当前布局组件的背景图如何填充组件区域。",
    usage: "强制铺满会拉伸到宽高，完整显示会保持比例并可能留边，裁切铺满会保持比例并可能裁掉边缘。",
    effect: "会写入 ui/layout.json 的 style.backgroundFit；旧布局或未设置时按强制铺满处理。",
  },
  "layout.pixelPreview": {
    title: "像素预览",
    purpose: "把当前百分比坐标换算成布局设计器画布里的像素位置。",
    usage: "用于核对当前断点下控件大概占多少屏幕空间；真正保存的仍是百分比，不是固定像素。",
    effect: "只用于检查，不改变项目数据；GameCLI 会在运行时按玩家窗口尺寸重新计算。",
  },
  "layout.copyBreakpoint": {
    title: "同步断点布局",
    purpose: "把当前组件在当前断点下的位置和尺寸复制到桌面、手机或两个断点。",
    usage: "先调好一个断点，再点击对应按钮快速复用；之后仍可切换断点单独微调。",
    effect: "会修改当前组件的 rect 或 mobileRect，保存布局后会进入导出的 ui/layout.json。",
  },
  "advanced.tab.settings": {
    title: "项目设置",
    purpose: "编辑项目名称、作者和玩家端外观相关设置。",
    usage: "在这里维护项目元数据和创作环境外观。",
    effect: "这些设置主要影响编辑器体验，不再暴露开发期接线配置。",
  },
  "advanced.tab.novel": {
    title: "小说导入",
    purpose: "把长篇小说文本清洗、拆章、拆场景，并逐步生成 AgentVN 场景蓝图。",
    usage: "导入小说文件后按步骤复核章节、角色和场景，再让模型分批写入画布。",
    effect: "会向当前工程追加节点和连线；已写入的内容可继续在场景编辑器中人工调整。",
  },
  "advanced.tab.assets": {
    title: "素材生成",
    purpose: "使用已配置的生成模型创建背景、角色、UI 图和其他素材草稿。",
    usage: "输入用途明确的提示词，生成后可保存到素材库并在场景或客户端视觉设置中引用。",
    effect: "会写入素材清单和生成历史；不会自动替换现有场景资源，除非你手动选择保存和应用。",
  },
  "advanced.tab.library": {
    title: "素材库",
    purpose: "管理当前项目已经导入或生成的背景、立绘、音频、UI 图片和字体素材。",
    usage: "需要整理文件夹、查找 asset_id、删除素材或打开素材所在分组时使用。",
    effect: "素材库变更会影响后续引用和导出资源清单；已被命令引用的素材删除前应先确认替换。",
  },
  "advanced.tab.animation": {
    title: "动画编辑",
    purpose: "管理可复用的演出动画模板、补间参数和动画资源。",
    usage: "当立绘动效工作室以外还需要整理通用动画模板时进入这里。",
    effect: "保存后的动画配置可被事件命令引用，并在导出后由 GameCLI 按运行时动画逻辑播放。",
  },
  "animation.templatePicker.close": {
    title: "关闭动画模板选择",
    purpose: "收起当前动画模板弹窗，保留已经选择的模板和参数。",
    usage: "浏览完模板或需要回到动画编辑面板时点击。",
    effect: "只关闭选择浮层，不会清空当前动画配置。",
  },
  "advanced.tab.preview": {
    title: "预览窗口",
    purpose: "使用 GameCLI 容器检查当前项目的真实播放效果。",
    usage: "把当前工程同步成临时卡带后打开或刷新预览。",
    effect: "预览不会改动正式导出文件，但会覆盖上一次临时预览卡带。",
  },
  "advanced.tab.providers": {
    title: "模型/连接",
    purpose: "配置文本、图像、语音等模型供应商，以及本地后端连接状态。",
    usage: "当助手、小说导入或素材生成无法调用模型时，先在这里检查模型、密钥和后端连接。",
    effect: "这些配置只用于编辑器创作流程，不会写入导出的玩家卡带。",
  },
  "advanced.tab.history": {
    title: "生成历史",
    purpose: "查看本项目近期通过模型生成的素材记录和请求摘要。",
    usage: "需要回找刚生成的图片、确认来源模型或复用素材提示时打开。",
    effect: "历史记录辅助追踪创作过程，不会改变剧情节点；保存素材后才会进入项目素材清单。",
  },
  "advanced.tab.layout": {
    title: "客户端布局",
    purpose: "编辑玩家客户端里标题页、播放页、设置页、存档页等界面组件的位置、尺寸和基础外观。",
    usage: "需要移动对白框、设置面板、快捷菜单、选项列表，或分别调整桌面与手机横屏布局时进入这里。",
    effect: "保存布局后会写入项目 runtimeUILayout，并随导出的 ui/layout.json 一起进入 .vncart；玩家客户端只读取结果，不提供二次编辑。",
  },
  "advanced.tab.theme": {
    title: "客户端主题",
    purpose: "编辑玩家客户端的主题配色、字体和控件样式。",
    usage: "需要微调某类控件时，在右侧“作用控件”中选择对应项目；滑杆配色也是其中一个小项。",
    effect: "保存后写入项目 runtimeUILayout 和导出的 ui/layout.json；GameCLI 玩家端只应用这些颜色，不允许玩家在客户端修改。",
  },
  "theme.preset": {
    title: "主题预设",
    purpose: "从内置配色方案快速生成 GameCLI 主题。",
    usage: "悬停或键盘聚焦预设按钮会显示真实 UI 预览；点击会把预设应用到当前主题草稿。",
    effect: "会修改主题 token 和主要控件样式，但不会保存，需点击保存主题后才写入项目。",
  },
  "theme.previewScreen": {
    title: "主题预览页面",
    purpose: "切换标题页、对白页、设置页和存档页的主题缩略预览。",
    usage: "调整颜色或控件样式时切换页面，检查不同控件的可读性和层次。",
    effect: "只影响预览视图，不改变剧情或导出内容。",
  },
  "theme.scope": {
    title: "主题作用控件",
    purpose: "选择本次自定义要作用到全局 token 还是某一类 GameCLI 控件。",
    usage: "全局主题适合统一改色；对白框、人物名牌、选项、设置组等适合做局部微调。",
    effect: "控件级样式会写入对应 UILayoutComponent.style，并覆盖同名主题 token。",
  },
  "theme.colorToken": {
    title: "基础与控件颜色",
    purpose: "设置 GameCLI 运行时复用的基础语义颜色。",
    usage: "优先调整背景、面板、主文字、强调色、对白框、人物名牌、选项和控件这些核心 token。",
    effect: "非法颜色会阻断保存；低对比会在主题体检中显示警告。",
  },
  "theme.sliderColorToken": {
    title: "滑杆颜色",
    purpose: "设置玩家客户端滑杆的轨道、进度和按钮颜色。",
    usage: "在客户端主题右侧“作用控件”选择“滑杆配色”；切换到设置页预览可检查效果。",
    effect: "会写入 ui/layout.json 的 colorSliderTrack、colorSliderActive、colorSliderThumb。导出后 GameCLI 只读取并渲染这些颜色，不提供玩家端修改入口。",
  },
  "theme.componentColor": {
    title: "控件颜色",
    purpose: "为当前作用控件单独设置背景、文字、强调和边框颜色。",
    usage: "用于让对白框、选项、快捷菜单或存档格和全局主题有细微区分。",
    effect: "这些值会覆盖对应控件从全局 token 继承的颜色。",
  },
  "theme.customNumber": {
    title: "主题数值",
    purpose: "调整字号、字重、圆角、间距、动效比例等主题数值。",
    usage: "保持字号可读、圆角不过度，并避免把动效比例设置得过高。",
    effect: "越界数值会在保存或导出前被结构校验阻断。",
  },
  "theme.fontStyle": {
    title: "字体样式",
    purpose: "设置当前控件文字使用正常或斜体。",
    usage: "斜体适合旁白、提示或特殊风格控件，不建议用于大段对白正文。",
    effect: "会写入 fontStyle，GameCLI 只接受 normal 或 italic。",
  },
  "theme.shadow": {
    title: "控件阴影",
    purpose: "设置当前控件是否使用无阴影、柔和阴影或强阴影。",
    usage: "对白框和设置面板适合柔和阴影，浮层或重点面板可使用强阴影。",
    effect: "会影响控件在 GameCLI 中的层次感。",
  },
  "theme.resetScope": {
    title: "重置当前控件",
    purpose: "把当前作用控件恢复为默认 skin 的样式。",
    usage: "当局部调色影响可读性或层次时使用，不会重置其他控件。",
    effect: "如果当前作用对象是全局主题，会恢复默认主题 token。",
  },
  "theme.restoreDefault": {
    title: "恢复默认主题",
    purpose: "把整个客户端主题恢复为 AgentVN 默认运行时 skin。",
    usage: "用于放弃当前主题草稿，重新回到默认蓝黑运行时外观。",
    effect: "会重置所有主题 token 和控件样式，保存后才写入项目。",
  },
  "theme.save": {
    title: "保存主题",
    purpose: "把当前主题草稿保存到项目的玩家端主题布局。",
    usage: "确认主题体检没有阻断错误后点击保存。",
    effect: "保存后的主题会随 GameCLI 预览和 .vncart 导出一起生效。",
  },
  "theme.validation": {
    title: "主题体检",
    purpose: "显示当前主题的结构错误和可读性警告。",
    usage: "阻断错误必须修复；低对比警告建议在导出前处理。",
    effect: "体检复用导出校验，避免玩家端静默 fallback。",
  },
  "settings.projectTitle": {
    title: "项目名称",
    purpose: "设置工程和导出内容显示的作品名称。",
    usage: "填写清晰、稳定、便于识别的标题。",
    effect: "会影响工程元数据和部分导出文件名。",
  },
  "settings.author": {
    title: "作者",
    purpose: "记录作品作者或团队名称。",
    usage: "填写用于发布信息和工程识别的名称。",
    effect: "不会影响剧情逻辑，但会进入部分发布元数据。",
  },
  "toolbar.assistant": {
    title: "大模型助手",
    purpose: "打开 AgentVN 文档问答页面。",
    usage: "询问编辑器功能、控件用途或想实现某种效果时点击。",
    effect: "会调用已配置的文本生成模型，并把相关文档片段作为参考上下文发送给后端。",
  },
  "toolbar.advanced": {
    title: "工具/设置",
    purpose: "打开高级工具面板，里面包含项目设置、客户端布局、客户端主题、素材、动画、预览和模型连接。",
    usage: "要修改玩家客户端界面时，从这里进入“客户端布局”或“客户端主题”。",
    effect: "这里的客户端布局和主题设置会保存到项目，并随 .vncart 导出；GameCLI 玩家端只读取这些设置，不提供配色编辑入口。",
  },
  "assistant.input": {
    title: "助手问题",
    purpose: "描述你想在 AgentVN 中实现的效果或遇到的操作问题。",
    usage: "可以问“如何添加背景音乐并预览？”；回车发送，Shift+Enter 换行。",
    effect: "问题会与检索到的本地文档片段一起发送给后端模型。",
  },
  "assistant.send": {
    title: "发送给助手",
    purpose: "把当前问题提交给大模型助手。",
    usage: "确认已经配置文本生成模型后点击。",
    effect: "会发起后端模型请求，不会直接修改项目内容。",
  },
  "assistant.clear": {
    title: "清空对话",
    purpose: "清除当前助手面板里的聊天记录和参考文档列表。",
    usage: "想重新开始提问时点击。",
    effect: "只影响前端显示，不会删除工程或模型配置。",
  },
  "assistant.quickQuestion": {
    title: "快捷提问",
    purpose: "把常见编辑问题直接填入并发送给大模型助手。",
    usage: "点击一个示例问题即可开始流式问答，也可以在输入框中自行改写。",
    effect: "会读取 AgentVN 文档索引和当前编辑上下文，不会直接修改项目。",
  },
  "notice.openReport": {
    title: "打开完整报告",
    purpose: "打开当前提示或报错的完整 AgentVN-Error-时间戳.txt 报告，方便定位模型、预览、导入导出等问题。",
    usage: "提示气泡只显示开头内容；需要完整错误、项目快照、运行环境和开发者排查信息时点击这里。",
    effect: "桌面版会写入并打开程序旁 error_log 下的时间戳报告；浏览器模式会打开或下载报告文件。报告会脱敏 Token，但会包含完整项目快照。",
  },
  "home.createProject": {
    title: "新建项目",
    purpose: "从项目主页创建一个新的 AgentVN 工程。",
    usage: "点击后进入项目创建流程，并随后进入主编辑器。",
    effect: "会生成新的项目元数据和初始节点；不会覆盖已有最近项目。",
  },
  "workbench.close": {
    title: "关闭事件工作台",
    purpose: "收起悬浮事件工作台，保留当前场景和事件列表。",
    usage: "当不需要继续快速添加对白、背景音乐、动画等事件时点击。",
    effect: "只关闭浮窗，不删除已添加的事件；再次选中场景可重新打开工作台。",
  },
  "workbench.minimize": {
    title: "最小化事件工作台",
    purpose: "只隐藏悬浮事件工作台，右侧场景事件编辑和当前选中节点都会保留。",
    usage: "当素材列表或快速添加面板遮挡编辑区域时点击；需要继续添加事件时再从右侧入口打开。",
    effect: "不会删除事件、不会切换节点、不会关闭右侧场景编辑。",
  },
  "novel.generateBlueprintLine": {
    title: "生成蓝图线",
    purpose: "把已切分的小说场景逐个改编成 AgentVN 场景节点，并立即追加到画布。",
    usage: "确认章节、场景和角色后点击。空白蓝图会自动从入口节点接入主工程线；已有蓝图会在空白区域生成独立小说工程线。",
    effect: "会持续向当前工程写入节点和连线，并给节点标注“来源于解析小说”；取消前已经生成的节点会保留。",
  },
  "novel.aiStart": {
    title: "AI 解析小说",
    purpose: "让大模型分批阅读全文，生成全书大纲、章节、角色和后续蓝图生成计划。",
    usage: "选择小说文件并确认文本生成模型已配置后点击。200KB 长文会按上下文预算分块请求模型，不会一次性塞入全部文本。",
    effect: "会消耗模型额度并进入大纲确认页；不会立即覆盖蓝图，只有确认大纲后才开始写入节点。",
  },
  "novel.confirmOutline": {
    title: "确认大纲并生成蓝图",
    purpose: "确认 AI 对全文的理解，并开始自动规划场景与逐个写入节点。",
    usage: "先复核章节、角色和主线摘要；发现明显错误可先修改标题、摘要或角色编号。",
    effect: "空白蓝图会连接入口主线，已有蓝图会另开小说工程线；生成过程可暂停、跳过或取消。",
  },
  "novel.pauseBlueprint": {
    title: "暂停蓝图生成",
    purpose: "临时停止正在进行的小说节点生成。",
    usage: "想检查已生成节点、调整模型配置或暂缓请求时点击。",
    effect: "已写入的节点会保留，之后可从当前进度继续。",
  },
  "novel.resumeBlueprint": {
    title: "继续蓝图生成",
    purpose: "从暂停位置继续生成小说蓝图节点。",
    usage: "确认已生成内容没有问题后点击。",
    effect: "会继续调用模型并追加后续节点，不会删除已生成节点。",
  },
  "novel.skipScene": {
    title: "跳过当前场景",
    purpose: "让生成流程略过当前卡住或不重要的小说场景。",
    usage: "当某个场景反复失败或想稍后人工处理时点击。",
    effect: "该场景会记录为跳过，流程继续处理后面的场景。",
  },
  "novel.cancelBlueprintLine": {
    title: "取消蓝图生成",
    purpose: "请求停止正在进行的小说蓝图渐进生成。",
    usage: "当小说过长、切分不理想或想先检查已生成节点时点击。",
    effect: "不会删除已经写入画布的节点；下一次可以继续从当前进度附近生成。",
  },
  "novel.reset": {
    title: "重新开始小说导入",
    purpose: "清空当前小说导入会话，回到导入入口。",
    usage: "换一本小说、模型误解严重或想重新扫描全文时点击。",
    effect: "只清空小说导入面板状态，不会删除已经写入画布的节点。",
  },
  "novel.chapterSummary": {
    title: "章节摘要",
    purpose: "复核或修改 AI 对该章节的理解。",
    usage: "用一两句话写清本章发生了什么、人物目标和转折。",
    effect: "会影响后续场景规划和节点生成的上下文。",
  },
  "novel.removeChapter": {
    title: "移除章节",
    purpose: "从 AI 大纲中删除明显错误或重复的章节。",
    usage: "确认该章节不是正文内容或已经被其他章节覆盖后再点击。",
    effect: "后续不会为该章节规划场景，也不会生成对应节点。",
  },
  "novel.resultReadable": {
    title: "可读视图",
    purpose: "用更适合人工复核的方式查看 AI 解析结果。",
    usage: "当你想快速检查章节、角色、时间线和场景计划是否合理时使用。",
    effect: "只切换结果展示方式，不会重新请求模型或修改蓝图。",
  },
  "novel.resultJson": {
    title: "JSON 视图",
    purpose: "查看后端校验通过或归一化后的原始结构化数据。",
    usage: "排查导入结果、字段缺失或需要反馈给开发者时切换到这里。",
    effect: "只读展示结构化数据，不会覆盖章节、大纲或已生成节点。",
  },
  "command.choice.displayName": {
    title: "选项中文代称",
    purpose: "给选项分支设置便于创作者识别的中文名称。",
    usage: "现在与选项文案共用同一个输入框，填写后会同步到 choice_display_name 和 text。",
    effect: "编辑器显示和玩家看到的选项会保持一致。",
  },
  "command.sprite.characterTarget": {
    title: "角色目标",
    purpose: "选择当前立绘命令要控制的角色 ID。",
    usage: "优先选择已有角色；需要新角色时可以输入稳定 ID，例如 alice 或 lin_che。",
    effect: "导出后会写入 sprite.character_id，并用于角色立绘动画目标追溯。",
  },
  "command.sprite.layer": {
    title: "人物遮挡层级",
    purpose: "控制多人场景中角色立绘的前后遮挡关系。",
    usage: "数值越大越靠前；留空会继承该角色当前层级，输入 0 可恢复默认层级。",
    effect: "会写入 sprite.layer；只改变遮挡关系，不改变人物位置、切换动效或当前角色选择。",
  },
  "command.sprite.animationConfig": {
    title: "角色立绘动画",
    purpose: "为角色立绘显示、隐藏或强调动作绑定结构化动画配置。",
    usage: "选择淡入淡出、位移、补间或预设后，再设置阶段、方向、时长、缓动和是否等待完成。",
    effect: "会写入 sprite.animation_config；GameCLI 按角色 ID 播放立绘动画，旧 animation 字符串仍保留兼容。",
  },
  "command.sprite.animationConfig.kind": {
    title: "立绘动画类型",
    purpose: "决定立绘动画的基本模式。",
    usage: "none 表示不播放；fade 用于淡入淡出；move 用于位移；tween 用关键帧补间；preset 使用预设。",
    effect: "非法类型会在导出或卡带导入校验中阻断。",
  },
  "command.sprite.animationConfig.phase": {
    title: "立绘动画阶段",
    purpose: "说明动画是入场、退场还是可见状态下的强调。",
    usage: "显示立绘常用 enter，隐藏立绘常用 exit，震动或心跳等强调动作用 emphasis。",
    effect: "退场动画会让 GameCLI 等动画结束后再移除立绘。",
  },
  "command.sprite.animationConfig.direction": {
    title: "立绘动画方向",
    purpose: "控制位移动画从哪个方向进入、退出或强调偏移。",
    usage: "move 类型通常选择 left、right、up 或 down；fade 可以保持 center 或 none。",
    effect: "会影响运行时生成的 x/y 位移关键帧。",
  },
  "command.sprite.animationConfig.duration": {
    title: "立绘动画时长",
    purpose: "设置角色立绘动画持续时间，单位毫秒。",
    usage: "常用 300-800ms；过短会显得突兀，过长会拖慢剧情节奏。",
    effect: "校验要求在 80 到 10000ms 之间。",
  },
  "command.sprite.animationConfig.delay": {
    title: "立绘动画延迟",
    purpose: "设置动画开始前等待多久，单位毫秒。",
    usage: "用于让多个角色或镜头错开启动；普通立绘动作可保持 0。",
    effect: "GameCLI 会把延迟计入阻塞等待和动画清理时间。",
  },
  "command.sprite.animationConfig.easing": {
    title: "立绘动画缓动",
    purpose: "控制动画速度曲线。",
    usage: "入场通常用 ease-out，退场可用 ease-in，强调动作可用更有弹性的 cubic-bezier。",
    effect: "会传给 GameCLI 的 Web Animations API。",
  },
  "command.sprite.animationConfig.origin": {
    title: "立绘动画锚点",
    purpose: "设置缩放和旋转围绕哪个点发生。",
    usage: "立绘常用 center bottom，让缩放像从脚底站稳；也可用 50% 100%。",
    effect: "会写入 transform_origin，运行端在播放动画前应用到目标元素。",
  },
  "command.sprite.animationConfig.displayName": {
    title: "立绘动画显示名",
    purpose: "给当前动画配置一个便于识别的作者侧名称。",
    usage: "填写如“左侧滑入”“轻微心跳”“退场淡出”等短名称。",
    effect: "只影响编辑器展示和助手说明，不改变运行时动画逻辑。",
  },
  "command.sprite.animationConfig.presetId": {
    title: "立绘动画预设 ID",
    purpose: "指定 preset 类型使用的运行时预设。",
    usage: "可使用 sprite_shake、sprite_heartbeat，或项目约定的自定义预设 ID。",
    effect: "GameCLI 会按预设 ID 编译对应关键帧；未知预设会退化为通用淡入/淡出式关键帧。",
  },
  "command.sprite.animationConfig.blocking": {
    title: "等待立绘动画结束",
    purpose: "决定剧情是否等待当前立绘动画播放完成。",
    usage: "关键入场、退场或强节奏演出可开启；普通立绘切换建议关闭以保持对白流畅。",
    effect: "开启后导出 blocking=true，GameCLI 会等待动画完成再继续下一条命令。",
  },
  "command.animation.spriteTarget": {
    title: "动画角色目标",
    purpose: "为 AnimationCommand 选择要作用的角色立绘目标。",
    usage: "选择当前立绘、全部立绘或指定角色 ID；普通角色动画优先用这个控件而不是手写 target。",
    effect: "会导出为 sprite:selected、sprite:all 或 sprite:<character_id>。",
  },
  "command.animation.spriteTargetCustom": {
    title: "自定义动画角色 ID",
    purpose: "手动指定 AnimationCommand 的角色立绘目标 ID。",
    usage: "仅在目标不在列表中时填写；应与角色表、对白角色或立绘命令中的 character_id 保持一致。",
    effect: "导出校验会检查 sprite:<character_id> 是否可追溯，找不到会阻断。",
  },
  "start.loadingAnimation": {
    title: "载入动画",
    purpose: "设置 GameCLI 在进入故事前显示的载入动画。",
    usage: "默认使用圆环 boot animation，也可以导入视频或多张图片作为自定义载入动画。",
    effect: "会写入 script.loading_animation，并在导出时校验引用资产是否已打包。",
  },
  "start.loadingAnimation.default": {
    title: "默认圆环载入",
    purpose: "使用 GameCLI 内置的圆环 boot animation。",
    usage: "没有专门片头素材时选择此项。",
    effect: "导出为 loading_animation.kind=default，不需要额外资产。",
  },
  "start.loadingAnimation.video": {
    title: "视频载入动画",
    purpose: "使用一个视频资产作为 GameCLI 载入动画。",
    usage: "选择后导入 mp4、webm、mov 等视频文件。",
    effect: "导出为 loading_animation.kind=video，并要求 video_asset_id 指向 video 资产。",
  },
  "start.loadingAnimation.imageSequence": {
    title: "多图载入动画",
    purpose: "使用多张图片按顺序循环或切换作为载入动画。",
    usage: "导入多张图片后可设置每张图片的切换时间，默认 1000ms。",
    effect: "导出为 loading_animation.kind=image_sequence，图片帧作为 ui 资产打包。",
  },
  "start.loadingAnimation.videoImport": {
    title: "导入载入视频",
    purpose: "把本地视频文件加入素材库并绑定到载入动画。",
    usage: "选择适合启动阶段播放的短视频，避免体积过大影响启动速度。",
    effect: "会创建 video 类型资产并写入 loading_animation.video_asset_id。",
  },
  "start.loadingAnimation.imageImport": {
    title: "导入载入图片帧",
    purpose: "把多张本地图片加入素材库并作为载入动画帧序列。",
    usage: "按希望播放的顺序选择图片；导入后可以移除单帧或继续追加。",
    effect: "会创建 ui 类型资产并写入 loading_animation.image_asset_ids。",
  },
  "start.loadingAnimation.frameDuration": {
    title: "图片切换时间",
    purpose: "设置多图载入动画每张图片停留的毫秒数。",
    usage: "默认 1000ms；快速动效可降低，展示型启动图可提高。",
    effect: "会写入 loading_animation.frame_duration_ms。",
  },
  "novel.validationSummary": {
    title: "小说导入结构校验摘要",
    purpose: "展示 AI 结果写入项目图之前的结构校验状态。",
    usage: "查看通过、自动修复、阻断错误和警告数量，确认模型结果是否已安全入库。",
    effect: "阻断错误会停止写入；自动修复会保留修复说明和原始模型结果供复核。",
  },
  "novel.validationReport": {
    title: "小说导入校验报告",
    purpose: "查看最近几次小说导入结构校验的具体问题和修复记录。",
    usage: "当 scene_id、choice target、source mapping 或分支来源出错时，用这里定位具体场景。",
    effect: "报告仅记录校验和修复信息，不会替代模型原始响应。",
  },
  "novel.drawerToggle": {
    title: "小说导入抽屉展开",
    purpose: "展开或收起小说导入页的辅助信息面板。",
    usage: "需要查看解析结果、结构校验、质量报告或素材审计时展开；只想专注主流程时收起。",
    effect: "只改变页面展示，不会重新请求模型或修改项目图。",
  },
  "novel.assetAuditItem": {
    title: "小说导入缺失素材定位",
    purpose: "定位小说导入后仍缺少视觉或音频素材的场景节点。",
    usage: "点击可跳到对应节点，方便补背景、立绘、头像或可选演出素材。",
    effect: "不会自动生成素材，只帮助定位需要处理的节点。",
  },
  "package.assetPreflightItem": {
    title: "导出前素材体检项",
    purpose: "定位导出前发现的缺失、占位或可选素材问题。",
    usage: "点击条目跳到相关节点，补齐背景、立绘、头像或音频演出引用。",
    effect: "定位节点本身不改动卡带；未解决的阻断问题会继续阻止导出。",
  },
  "package.console.clear": {
    title: "清空导出控制台",
    purpose: "清除当前发布与打包日志面板中的历史显示。",
    usage: "准备重新导出前可以清空旧日志，便于观察本次输出。",
    effect: "只清除前端日志显示，不删除导出文件或错误报告。",
  },
  "animation.spriteTarget": {
    title: "动画编辑器角色目标",
    purpose: "在动画编辑器中选择 sprite 类型动画要作用的角色立绘。",
    usage: "选择当前立绘、全部立绘或已有角色 ID；需要特殊目标时再使用自定义输入。",
    effect: "会把目标写成 sprite:selected、sprite:all 或 sprite:<character_id>。",
  },
  "animation.spriteTargetCustom": {
    title: "动画编辑器自定义角色 ID",
    purpose: "手动输入 sprite 类型动画要作用的角色 ID。",
    usage: "仅在角色不在下拉列表中时使用，并保持与对白或立绘命令中的 character_id 一致。",
    effect: "导出校验会检查该角色是否可追溯。",
  },
  "asset.breadcrumb.root": {
    title: "素材库根目录",
    purpose: "返回素材库的散落素材视图。",
    usage: "在文件夹内浏览时点击，可回到未归档素材列表。",
    effect: "只切换素材库视图，不移动素材。",
  },
  "asset.breadcrumb.folder": {
    title: "素材库文件夹路径",
    purpose: "跳转到路径面包屑中的某个素材文件夹。",
    usage: "在多层整理素材时快速返回上级或指定文件夹。",
    effect: "只切换当前文件夹视图，不修改素材归档。",
  },
  "asset.folder.cancel": {
    title: "取消新建文件夹",
    purpose: "放弃当前正在输入的新文件夹名称。",
    usage: "误点新建文件夹或暂时不想创建时点击。",
    effect: "清空草稿，不会创建文件夹。",
  },
  "asset.batch.clearSelection": {
    title: "取消素材选择",
    purpose: "清除素材库当前批量选择状态。",
    usage: "批量移动或复制完成后点击，回到普通浏览模式。",
    effect: "不移动、不复制、不删除素材，只取消选中。",
  },
  "asset.folder.renameName": {
    title: "文件夹重命名输入",
    purpose: "编辑素材文件夹的新名称。",
    usage: "输入清晰的分类名称，例如 背景、角色立绘、UI 帧。",
    effect: "按保存后才会更新文件夹名称。",
  },
  "asset.folder.renameSave": {
    title: "保存文件夹重命名",
    purpose: "确认当前素材文件夹的新名称。",
    usage: "检查名称无误后点击保存。",
    effect: "只修改文件夹名称，不改变其中素材的 asset_id。",
  },
  "asset.selectAllVisible": {
    title: "全选当前素材",
    purpose: "选择当前视图中可见的素材卡片。",
    usage: "需要批量移动或复制当前文件夹素材时使用。",
    effect: "只影响当前可见素材的选择状态。",
  },
  "start.loadingAnimation.removeFrame": {
    title: "移除载入图片帧",
    purpose: "从多图载入动画序列中移除一张图片帧。",
    usage: "当某一帧顺序错误、画面不合适或不再需要时点击。",
    effect: "会从 loading_animation.image_asset_ids 中移除该帧引用，不会删除素材库里的原始资产。",
  },
  "preview.open": {
    title: "GameCLI 预览",
    purpose: "把当前工程导出为临时卡带，并交给 GameCLI 容器播放。",
    usage: "修改剧情、资源或布局后再次点击，会覆盖临时卡带并重新打开最接近正式玩家端的预览。",
    effect: "只影响预览缓存，不会覆盖正式卡带或发布包；浏览器开发模式无法启动 GameCLI 时会提示使用桌面版预览。",
  },
  "preview.close": {
    title: "关闭预览",
    purpose: "关闭由编辑器启动的 GameCLI 预览进程。",
    usage: "预览结束或需要重新干净启动时点击。",
    effect: "不会删除工程、正式导出文件或上一次临时预览卡带。",
  },
  "preview.screen": quickHelp("预览页面", "切换内嵌 GameCLI 当前显示的页面。", "用于检查标题、播放、设置和存档界面。", "只影响预览，不修改工程数据。"),
  "preview.reloadScene": quickHelp("重载当前场景", "从上一个场景的稳定状态重新进入当前预览场景。", "用于反复检查背景、立绘和镜头等场景入场过渡。", "只重播真实客户端预览，不修改工程或正式卡带。"),
  "preview.reloadSceneRoute": quickHelp("选择进入路线", "指定从哪一个上游场景进入当前场景。", "当前场景有多个前驱分支时，选择需要检查的那条路线。", "只影响本次重播，不会记住或修改剧情路线。"),
  "package.mode": {
    title: "发布形式",
    purpose: "选择本次要导出的发布类型。",
    usage: "游戏卡带会导出 .vncart；构建单游戏软件包会直接生成安装包；固定容器工程 ZIP 适合手动交给脚本继续构建。",
    effect: "会影响导出文件结构、是否需要选择输出目录，以及是否调用本机 Tauri/Android 工具链。",
  },
  "package.outputDir": {
    title: "软件包导出目录",
    purpose: "显示 .exe/.msi/.apk 将被复制到的本机目录。",
    usage: "构建单游戏软件包前必须先选择目录；浏览器开发模式不能使用这个能力。",
    effect: "只决定本次软件包产物输出位置，不会改变工程素材、卡带内容或 GameCLI 源码。",
  },
  "package.chooseOutputDir": {
    title: "选择目录",
    purpose: "打开系统目录选择器，指定软件包输出位置。",
    usage: "建议选择一个空目录或专门的发布目录，成功后这里只保留玩家需要拿走的安装包或 APK。",
    effect: "桌面版会记住本面板当前选择；取消选择不会开始构建。",
  },
  "package.export": {
    title: "导出发布包",
    purpose: "生成当前选择的卡带、固定容器工程，或真实单游戏安装包。",
    usage: "确认资源扫描和发布信息后再导出。",
    effect: "构建单游戏软件包时会先校验 .vncart，再只输出安装包/APK；manifest 和日志仅在失败时作为诊断信息保存在缓存目录。",
  },
  "provider.defaultModel": {
    title: "默认模型",
    purpose: "为 AgentVN 的两类模型入口指定实际使用的模型。",
    usage: "文本与联想模型负责剧情生成、小说导入、大模型助手和提示词优化；素材生成模型只负责图片/素材生成。",
    effect: "会影响后续功能发起请求时实际使用的模型，但不会修改项目剧情或素材内容。",
  },
  "provider.textFamilyModel": {
    title: "文本与联想模型",
    purpose: "指定剧情生成、小说导入、大模型助手和提示词优化共用的文本模型。",
    usage: "选择一个支持文本输出的模型；提示词优化不再单独选模型，也会使用这里的选择。",
    effect: "会统一影响所有文本链路，避免剧情生成和联想/提示优化使用不同模型。",
  },
  "provider.assetModel": {
    title: "素材生成模型",
    purpose: "指定用于生成背景、立绘、素材图片的模型。",
    usage: "请选择真实支持图片/素材生成的模型；普通聊天模型不要选在这里。",
    effect: "只影响素材生成面板，不会改变剧情生成、小说导入或大模型助手。",
  },
  "provider.textFamilyCapability": {
    title: "用于文本与联想",
    purpose: "标记该模型可以承担文本生成和提示词优化任务。",
    usage: "文本聊天、剧情续写、小说导入、大模型助手、提示词优化模型应勾选这一项。",
    effect: "会让该模型进入统一文本模型列表；旧的提示优化选择会自动回落到同一个文本模型。",
  },
  "provider.assetCapability": {
    title: "用于素材生成",
    purpose: "标记该模型可以生成图片素材。",
    usage: "只有图像生成、素材生成模型才勾选；纯文本模型不要勾选。",
    effect: "只勾选这一项时，文本生成参数会收起，模型会进入素材生成模型列表。",
  },
  "provider.toggleTokenVisibility": {
    title: "显示或隐藏 Token",
    purpose: "临时切换 API Token 输入框的可见状态，方便检查是否填错。",
    usage: "点击后显示明文或重新隐藏；在公共场合或截图前请保持隐藏。",
    effect: "只影响当前界面显示，不会改变已保存的 Token 内容。",
  },
  "provider.toggleModelDetails": {
    title: "展开模型详情",
    purpose: "展开或收起当前模型的 ID、能力、生成参数和测试按钮。",
    usage: "需要修改模型参数或检查能力勾选时展开；配置完成后可收起减少占用空间。",
    effect: "只改变设置面板显示状态，不会自动发起模型请求或修改项目剧情。",
  },
  "provider.structuredMode": {
    title: "结构化生成模式",
    purpose: "控制剧情生成最终数据来自结构化工具调用，还是退回旧的 JSON 兼容模式。",
    usage: "默认使用自动兼容；只有模型服务明确不支持结构化工具时，再临时切到 JSON 兼容。",
    effect: "结构化工具会让后端只接受通过 SceneBeat/MemoryUpdate 校验的数据，普通文本不会写入项目。",
  },
  "provider.requestTimeout": {
    title: "请求超时（秒）",
    purpose: "设置后端等待模型服务返回结果的最长时间，适合 deepseek-v4-pro、reasoner、thinking 等响应较慢的模型。",
    usage: "默认 300 秒；普通快速模型可调低，慢模型建议 300-600 秒，允许范围 30-900。",
    effect: "调大可以减少误判超时，但服务异常时会等待更久；前端会额外保留 30 秒缓冲，避免后端仍在等待时页面先断开。",
  },
  "provider.contextBudget": {
    title: "上下文预算",
    purpose: "设置文本模型单次请求可使用的大致上下文容量。",
    usage: "普通模型建议 24000 tokens；长上下文模型可调到 48000 以上。素材生成专用模型不需要填写这一项。",
    effect: "小说导入、助手问答和剧情生成会按该预算进行压缩、检索或切片，避免一次性塞入过多内容。",
  },
  "provider.systemPrompt": {
    title: "模型系统提示词",
    purpose: "为当前文本模型追加固定系统提示词，用来约束输出风格、格式习惯和创作偏好。",
    usage: "适合填写破盾、酒馆式角色/风格约束或固定写作要求；建议控制在必要内容内，最长 8000 字。",
    effect: "会参与剧情生成、小说导入、大模型助手和提示词优化等文本请求，但不能覆盖 AgentVN 的结构化写入和校验规则；素材生成模型不会使用这一项。",
  },
  "provider.testGeneration": {
    title: "测试生成",
    purpose: "用当前连接和模型参数发起一次短文本生成测试。",
    usage: "保存 API 地址、密钥和参数后点击，用来确认模型可用。",
    effect: "会请求后端和模型服务，但不会写入剧情或覆盖项目内容。",
  },
  "provider.compatibilityCheck": {
    title: "检查结构化生成兼容性",
    purpose: "检查当前文本模型是否能稳定返回 AgentVN 可写入的结构化剧情和记忆数据。",
    usage: "填写 Token 后点击，观察进度条和友好结果；界面不会暴露底层接口名称。",
    effect: "会发起一次短模型请求，并可能保存推荐的结构化模式；不会写入项目剧情或素材。",
  },
  "animation.category": {
    title: "动画分类",
    purpose: "切换模板库中显示的动画用途分类。",
    usage: "按立绘、背景或镜头等类别筛选，再选择适合当前演出的模板。",
    effect: "只改变模板选择范围，不会立即写入剧情节点。",
  },
  "animation.preset": {
    title: "动画模板",
    purpose: "选择一组预设关键帧和参数作为动画草稿。",
    usage: "根据推荐场景选择模板，再用快速微调修正目标、速度和方向。",
    effect: "会更新右侧草稿和预览，只有点击插入后才写入当前节点。",
  },
  "animation.direction": {
    title: "动画方向",
    purpose: "控制模板移动、进入或退出的方向。",
    usage: "按画面调度选择 left、right、up 或 down 等选项。",
    effect: "会改变生成关键帧的位置变化，方向错误会让角色或镜头运动反向。",
  },
  "animation.duration": {
    title: "动画时长",
    purpose: "控制动画从开始到结束所用的毫秒数。",
    usage: "常用 300-1000ms；强调演出可更长，快速反馈可更短。",
    effect: "时长会影响剧情节奏，阻塞动画还会影响后续命令何时继续。",
  },
  "animation.loop": {
    title: "循环播放",
    purpose: "决定动画是否在播放后持续重复。",
    usage: "适合呼吸、漂浮、雨幕等持续效果；一次性入场动画通常关闭。",
    effect: "开启后可能持续影响画面，直到后续命令覆盖或清除目标状态。",
  },
  "animation.target": {
    title: "动画目标",
    purpose: "指定动画要作用到哪个画面对象。",
    usage: "填写立绘角色编号、背景目标或 camera；编号应与命令和素材引用一致。",
    effect: "目标填错会导致动画无法作用到预期对象。",
  },
  "animation.blocking": {
    title: "等待动画结束",
    purpose: "控制剧情是否等动画播完再执行下一条命令。",
    usage: "关键转场、镜头推进建议开启；氛围循环或轻微动效可关闭。",
    effect: "开启会拉长玩家等待时间，关闭则可能与后续对白或动作同时发生。",
  },
  "animation.preview": {
    title: "预览播放",
    purpose: "在面板内播放当前动画草稿。",
    usage: "插入前先点击检查方向、速度、缩放和滤镜是否符合预期。",
    effect: "只影响预览舞台，不会写入当前剧情节点。",
  },
  "animation.previewSpriteAsset": {
    title: "立绘预览素材",
    purpose: "选择一张真实角色图像来检查当前立绘动效。",
    usage: "选择与目标角色和表情相符的立绘；它与动画作用的角色目标相互独立。",
    effect: "只更换动效工作室里的预览图，不会改写场景立绘命令或导出素材引用。",
  },
  "animation.previewBackgroundAsset": {
    title: "背景预览素材",
    purpose: "选择一张真实背景图来检查当前背景切换动效。",
    usage: "使用准备放入场景的背景图确认淡入、模糊或推进效果。",
    effect: "只更换动效工作室里的预览图，不会改写场景背景命令或导出素材引用。",
  },
  "animation.insert": {
    title: "插入动画",
    purpose: "把当前动画草稿写入选中的动画节点或场景节点。",
    usage: "确认选中目标节点后点击；场景节点会追加到命令列表末尾。",
    effect: "会修改当前节点内容，动画节点中已有动画指令会被覆盖。",
  },
  "animation.name": {
    title: "动画名称",
    purpose: "为动画草稿设置便于识别的显示名称。",
    usage: "填写短名称，例如“角色淡入”或“镜头轻推”。",
    effect: "主要影响编辑时识别，不直接改变动画播放参数。",
  },
  "animation.id": {
    title: "动画编号",
    purpose: "设置动画预设或草稿的内部编号。",
    usage: "使用稳定英文或下划线编号，例如 sprite_fade_in。",
    effect: "编号会随动画命令导出，重复或混乱会降低后续维护可读性。",
  },
  "animation.easing": {
    title: "缓动函数",
    purpose: "控制动画速度曲线。",
    usage: "常用 ease、ease-in-out、linear；也可填写 CSS cubic-bezier。",
    effect: "缓动会改变动作手感，错误值可能让运行端退回默认速度曲线。",
  },
  "animation.openStudio": {
    title: "打开动效工作室",
    purpose: "进入独立的大尺寸动画编辑器，使用时间轴和关键帧编辑立绘动效。",
    usage: "需要拖拽关键帧、预览补间、调整延迟或锚点时打开；普通微调可直接用当前面板。",
    effect: "只有点击应用后才会写回当前工作台或命令配置。",
  },
  "animation.spriteFocus": {
    title: "心理聚焦",
    purpose: "短暂压暗背景和陪衬角色，并轻微放大当前角色。",
    usage: "适合心理活动、内心独白、短暂失神或关键自省段落。",
    effect: "写入 sprite_focus 强调预设；效果播放一次、自动恢复，并且默认不阻塞后续对白。",
  },
  "animation.studioApply": {
    title: "应用动效配置",
    purpose: "把动效工作室中的草稿写回当前命令。",
    usage: "确认预览和关键帧后点击应用；取消或 Escape 不会保存草稿。",
    effect: "会更新 animation_config 或动画命令参数，后续导出到 GameCLI 播放。",
  },
  "animation.studioCancel": {
    title: "取消动效编辑",
    purpose: "关闭角色动画工作室并丢弃当前未应用的草稿。",
    usage: "预览或调参后不想写回命令时点击这里，或使用关闭按钮。",
    effect: "不会修改当前 sprite/animation 命令；已经点击应用的改动不受影响。",
  },
  "animation.keyframeOffset": {
    title: "关键帧时间点",
    purpose: "设置该关键帧位于动画进度的哪个位置。",
    usage: "填写 0 到 1 的小数，0 是开始，1 是结束。",
    effect: "时间点顺序错误会让动画跳动或节奏异常。",
  },
  "animation.keyframeEasing": {
    title: "关键帧段缓动",
    purpose: "设置从当前关键帧到下一关键帧之间的速度曲线。",
    usage: "入场可用 ease-out，机械动作可用 linear，强调动作可用 ease-in-out。",
    effect: "运行端会把它作为 Web Animations API 的 per-keyframe easing。",
  },
  "animation.keyframeOpacity": {
    title: "透明度",
    purpose: "设置该关键帧的不透明程度。",
    usage: "填写 0 到 1；0 完全透明，1 完全显示。",
    effect: "会影响淡入淡出表现，超出范围可能被运行端限制或表现异常。",
  },
  "animation.keyframeX": {
    title: "横向位移",
    purpose: "设置该关键帧在水平方向的位置偏移。",
    usage: "填写像素数，负数向左，正数向右，例如 -80 或 120。",
    effect: "会影响角色、背景或镜头的横向运动幅度。",
  },
  "animation.keyframeY": {
    title: "纵向位移",
    purpose: "设置该关键帧在垂直方向的位置偏移。",
    usage: "填写像素数，负数向上，正数向下，例如 -40 或 60。",
    effect: "会影响对象上下移动，数值过大可能移出画面。",
  },
  "animation.keyframeScale": {
    title: "缩放",
    purpose: "设置该关键帧的对象缩放倍率。",
    usage: "1 表示原始大小；1.08 表示轻微放大，0.9 表示缩小。",
    effect: "会影响镜头推近、角色强调或背景呼吸感。",
  },
  "animation.keyframeRotate": {
    title: "旋转",
    purpose: "设置该关键帧的旋转角度。",
    usage: "填写角度数，正数顺时针，负数逆时针。",
    effect: "会影响对象姿态，过大数值可能造成突兀演出。",
  },
  "animation.keyframeBlur": {
    title: "模糊",
    purpose: "设置该关键帧的模糊强度。",
    usage: "填写像素值，例如 0、2、6；越大越虚。",
    effect: "会影响转场、景深或失焦效果，过高会降低画面可读性。",
  },
  "animation.keyframeBrightness": {
    title: "亮度",
    purpose: "设置该关键帧的亮度倍率。",
    usage: "1 为正常亮度，0.7 变暗，1.2 变亮。",
    effect: "会影响氛围和闪白效果，极端值可能造成视觉不适。",
  },
  "animation.expertMode": {
    title: "专家模式",
    purpose: "控制是否显示自定义 CSS 输入入口。",
    usage: "普通动画只用模板、滑杆和关键帧控件；只有模板无法表达特殊样式时再开启。",
    effect: "开启后会显示 CSS 文本框，错误样式可能被运行端忽略；关闭不会删除已经填写的关键帧数值。",
  },
  "animation.keyframeCustomCss": {
    title: "自定义 CSS",
    purpose: "补充关键帧中未覆盖的样式属性。",
    usage: "填写合法 CSS 声明，例如 filter: saturate(1.2);。",
    effect: "错误 CSS 可能被浏览器忽略，也可能覆盖模板生成的视觉效果。",
  },
  "animation.deleteKeyframe": {
    title: "删除关键帧",
    purpose: "移除当前动画时间线中的一个关键帧。",
    usage: "确认该时间点不再需要后点击删除。",
    effect: "会改变动画轨迹，删除起点或终点可能让动画缺少明确状态。",
  },
  "animation.addKeyframe": {
    title: "添加关键帧",
    purpose: "在时间线末尾新增一个关键帧。",
    usage: "添加后填写时间点、透明度、位移、缩放等参数。",
    effect: "会让动画轨迹更复杂，关键帧越多越需要检查节奏是否自然。",
  },
  "command.drag": {
    title: "拖拽事件",
    purpose: "调整当前场景内事件卡片的播放顺序。",
    usage: "按住手柄上下拖动，找到空隙后松手插入。",
    effect: "会改变剧情执行顺序，后面的卡片会让位并随新顺序保存。",
  },
  "command.expand": {
    title: "展开事件卡片",
    purpose: "在标签态和参数编辑态之间切换。",
    usage: "点击卡片摘要展开或收起参数；最多同时展开三张。",
    effect: "只影响编辑视图，不改变事件内容。",
  },
  "command.more": {
    title: "事件操作菜单",
    purpose: "收纳低频或危险操作。",
    usage: "点击后可执行删除等操作。",
    effect: "删除会移除当前事件卡片，请确认后再操作。",
  },
  "workbench.commandType": {
    title: "事件类型",
    purpose: "选择要主动添加到当前场景的事件类型。",
    usage: "点击分类卡片里的按钮，在文本叙事、画面角色、分支状态、音频节奏和演出镜头之间切换。",
    effect: "新事件会追加到场景事件列表末尾。",
  },
  "workbench.addCommand": {
    title: "添加事件",
    purpose: "把浮动工作台中配置的事件加入当前场景。",
    usage: "先选择事件类型并填写快捷参数，再点击添加。",
    effect: "事件会出现在编辑台末尾，列表会自动滚动到底部并展开新卡片。",
  },
  "workbench.resize": {
    title: "调整工作台大小",
    purpose: "改变浮动事件工作台的宽度和高度。",
    usage: "拖拽右下角手柄，按当前屏幕空间调整。",
    effect: "尺寸会保存到本机，下次打开编辑器继续沿用。",
  },
  "palette.scene": {
    title: "场景节点",
    summary: "场景节点是剧情主载体。真正会导出到 Runtime、最终被玩家看到的对白、旁白、背景切换、选项分支，通常都应该写在这里。",
    whenToUse: "适用时机\n当你要承载一段完整可播放剧情，或者需要让 AI 基于当前内容继续往下写时，就使用场景节点。",
    howToUse: "操作步骤\n1. 先填写场景标题、摘要和章节编号。\n2. 在命令列表中添加旁白、对白、背景、立绘、选项等命令。\n3. 如果要让 AI 续写，先写清楚作者目标，再点击“辅助生成后续”。",
    wiring: "连线方式\n场景节点通常从入口节点、条件节点或其他场景节点连入；底部默认出口连到下一段剧情。若场景内已有 choice 命令，真正的分支走向优先由选项目标决定。",
    bestPractices: "最佳实践\n一个场景只承载一个明确的戏剧动作，例如“到站重逢”或“冲突升级后做出选择”。摘要写成可检索的短说明，方便自己回看，也方便 AI 和记忆系统理解上下文。",
    pitfalls: "常见误区\n不要把多个时间段、多个地点、多个情绪转折硬塞进一个场景节点。也不要把状态修改和条件判断只写在对白里却不拆成独立节点，这样后续很难维护。",
    example: "最佳示例\n场景设定：主角深夜抵达旧车站，第一次见到在雨里等待她的青梅竹马。\n节点配置：标题“旧车站重逢”，摘要“雨夜重逢，气氛克制但旧事未解”，命令依次为背景切到 station_rain、旁白一条、角色对白两条、最后给一个选项。\n连线结果：从入口节点连到该场景；玩家做出选项后，再分到“解释迟到原因”或“先转移话题”两个后续场景。",
  },
  "palette.choice": {
    title: "选项分支节点",
    summary: "选项分支节点把玩家选择从场景命令里提到画布层级。它适合让关键分支在蓝图上清晰可见，同时保留每个选项独立连线到不同后续节点的能力。",
    whenToUse: "适用时机\n当一个选择会明显改变故事路线、进入不同章节、触发不同结局，或你希望回看蓝图时一眼看清分支结构，就使用选项分支节点。简单的一两个即时选择仍然可以继续放在场景编辑器的 choice 命令里。",
    howToUse: "操作步骤\n1. 在左侧节点栏新增“选项分支节点”。\n2. 在右侧检查器里编辑每个选项的稳定编号、显示名称和玩家看到的文本。\n3. 从节点底部对应选项手柄连到目标场景、修饰节点、条件节点或结局路线。",
    wiring: "连线方式\n选项分支节点上方接入前置剧情，底部每个选项都有独立出口。导出时，系统会根据每条选项连线自动写入 target_scene_id；如果没有连线，也可以手动填写目标场景编号作为兼容路径。",
    bestPractices: "最佳实践\n把分支节点放在关键剧情抉择之后，并让选项文案表达玩家的真实意图，例如“坦白真相”而不是“路线 A”。如果选项会改变变量，建议先连到修饰节点写入状态，再进入后续场景或条件节点。",
    pitfalls: "常见误区\n不要把所有小选择都拆成独立分支节点，否则画布会变得过碎。也不要频繁修改 choice_id；已有连线依赖这个编号，改名后需要重新检查分支出口。",
    example: "最佳示例\n场景设定：雨夜车站，主角必须决定是否告诉林澈第七号柜的真相。\n节点配置：选项一 choice_truth，文本“坦白真相”；选项二 choice_hide，文本“隐瞒线索”。\n连线结果：choice_truth 连到“记录坦白”修饰节点，再进入信任路线；choice_hide 连到“记录隐瞒”修饰节点，再进入地下通道路线。",
  },
  "palette.modifier": {
    title: "修饰节点",
    summary: "修饰节点专门用来修改 Runtime 变量，例如旗标、数值、解锁状态。它负责记录“状态变化”，而不是承载剧情正文。",
    whenToUse: "适用时机\n当剧情走到某一步需要记录“是否见过某人”“好感度 +1”“钥匙已获得”这类状态时，就用修饰节点。",
    howToUse: "操作步骤\n1. 填写变量名，例如 met_alice、favor_alice 或 ticket_count。\n2. 选择操作类型，如 set、add、subtract、toggle。\n3. 填写值后，把它插在对应剧情节点之后。",
    wiring: "连线方式\n最常见结构是“场景节点 -> 修饰节点 -> 下一个场景/条件节点”。如果状态只在某条分支成立，就把修饰节点挂在那条分支上，而不是放在公共主线上。",
    bestPractices: "最佳实践\n变量名保持语义明确，布尔旗标用 has_/is_/met_ 风格，数值变量用看得懂的业务名。把每次状态修改拆开写，后面查条件时会非常清楚。",
    pitfalls: "常见误区\n不要把角色设定、剧情摘要这类长期信息塞进修饰节点；它只适合轻量运行状态。也不要把多个不相干的修改意图混在一个节点里。",
    example: "最佳示例\n场景设定：玩家在雨夜把伞借给女主。\n节点配置：变量名 favor_alice，操作 add，变量值 1。\n连线结果：在“借伞”场景之后接一个修饰节点，再进入下一场景；后续条件节点可以用 favor_alice >= 3 来判断是否开放亲密支线。",
  },
  "palette.condition": {
    title: "条件节点",
    summary: "条件节点负责根据 Runtime 变量把剧情分成真假两路。它让“是否满足某条件”这件事在图里显式可见。",
    whenToUse: "适用时机\n当你要判断玩家是否满足某数值、是否触发过某事件、是否拿到某道具，或者想根据前序状态改变剧情走向时，就应该使用条件节点。",
    howToUse: "操作步骤\n1. 用可视化构建器选择变量、变量类型、判断方式和比较值，例如 favor_alice / 数字 / 大于等于 / 3。\n2. 为“满足时”和“不满足时”两个出口命名，让图上一眼看懂含义。\n3. 分别把两个出口连到不同后续节点；旧工程或特殊判断可以展开高级表达式继续手写。",
    wiring: "连线方式\n条件节点通常接在场景节点或修饰节点之后，再从两个出口分别连向两条线路。出口标签最好写成“已达成”“未达成”这类剧情语义，而不是只写 true/false。",
    bestPractices: "最佳实践\n优先使用构建器生成结构化条件，只有复杂判断才使用高级表达式。让每个条件尽量单一、可读；复杂逻辑宁可拆成多个条件节点，也不要堆成一长串难维护表达式。出口名写成剧情含义，回头查图会轻松很多。",
    pitfalls: "常见误区\n不要把条件判断藏在选项文案或场景摘要里却不建条件节点，那样图上看不出分支依据。也不要让真假两路都绕回同一点却没有明确目的。",
    example: "最佳示例\n场景设定：玩家准备进入图书馆禁书区。\n节点配置：表达式 has_library_key == true，trueLabel 写“持有钥匙”，falseLabel 写“没有钥匙”。\n连线结果：真出口连到“进入禁书区”场景，假出口连到“被管理员拦下”场景，之后两条线再在更后面的公共剧情汇合。",
  },
  "palette.animation": {
    title: "旧版独立动画节点",
    summary: "独立动画节点已经停止新建。旧工程中的节点仍可编辑和导出，也可以一键迁移到相邻场景事件或原地转成普通场景。",
    whenToUse: "适用时机\n只在维护旧工程时处理这种节点。新动画请直接添加到场景事件列表，运镜请使用“＋ 运镜”打开运镜工作室。",
    howToUse: "操作步骤\n1. 选中旧版动画节点。\n2. 查看转换面板给出的安全落点。\n3. 优先移到后续场景开头或前置场景末尾；分支复杂时选择原地转成普通场景。",
    wiring: "连线方式\n转换器会分析前后连线。安全吸收时会自动重连；原地转换会保留节点编号、位置和全部连线。",
    bestPractices: "最佳实践\n动画和运镜都作为场景事件维护，剧情蓝图只保留真正影响路线结构的节点。",
    pitfalls: "常见误区\n不要为了兼容旧作品继续手工制造独立动画节点，也不要把旧版整屏相机动画误当成新版只移动世界层的运镜。",
    example: "最佳示例\n旧工程结构为“看到照片 → 闪白动画 → 震惊质问”。若后续场景只有这一个入口，选择“移到后续场景开头”，动画会成为该场景第一条事件，播放顺序保持不变。",
  },
  "palette.start": {
    title: "入口节点",
    summary: "入口节点是整个项目的唯一起点。导出剧本时，玩家从它指向的第一条连线开始播放。",
    whenToUse: "适用时机\n每个项目只需要一个入口节点。它不是剧情内容本身，而是告诉系统“玩家最先从哪里进入故事”。",
    howToUse: "操作步骤\n1. 保持项目中只有一个入口节点。\n2. 把它连到真正的开场场景。\n3. 如果要更换开场，只改入口节点的第一条连线目标。",
    wiring: "连线方式\n入口节点通常只需要一条主线连到首个场景节点。它不适合作为普通分支节点反复参与流程判断。",
    bestPractices: "最佳实践\n让入口后立刻进入故事第一拍，不要先接一串技术性节点。若确实需要初始旗标，优先在第一个场景后再接修饰节点，而不是把入口本身做成流程中枢。",
    pitfalls: "常见误区\n不要创建多个入口节点；也不要让入口直接连到结局或无剧情内容节点，否则导出后的开场体验会非常奇怪。",
    example: "最佳示例\n场景设定：作品以“雨夜到站”开场。\n节点配置：入口节点本身不需要复杂字段，只需把唯一连线指向“旧车站重逢”场景。\n连线结果：玩家启动游戏后，会从这个开场场景直接开始播放。",
  },
  "palette.end": {
    title: "结局节点",
    summary: "结局节点用于显式结束一条线路，并记录结局编号与标题。它适合有“结局收束”语义的终点，而不是普通场景暂时停住。",
    whenToUse: "适用时机\n当某条线路已经完成表达，需要作为可识别结局收尾，比如普通结局、真结局、坏结局、隐藏结局时，就使用结局节点。",
    howToUse: "操作步骤\n1. 填写 ending_id，保证后续统计或图鉴能识别。\n2. 填写 ending_title，让玩家端能显示结局名称。\n3. 把通往终点的剧情节点连到这个结局节点。",
    wiring: "连线方式\n结局节点通常只作为终点被连入，不再继续向后连接。如果一条线路只是阶段性暂停，应该继续使用场景节点，而不是过早接到结局节点。",
    bestPractices: "最佳实践\n让结局编号稳定、标题可读，最好和你的结局规划保持一致。不同线路在图上用结局节点收束，会让整体结构非常清楚。",
    pitfalls: "常见误区\n不要把普通“本章结束”也做成结局节点，除非它真的代表玩家线路结束。也不要只写标题不写 ending_id，后续统计能力会明显变弱。",
    example: "最佳示例\n场景设定：玩家选择独自离开小镇，再也没有回头。\n节点配置：ending_id=ending_leave_town，ending_title=“雾中远行”。\n连线结果：从“离站背影”场景连到该结局节点，Runtime 会把它导出为明确的结局终点，而不是普通过场场景。",
  },
  "toolbar.timeline": {
    title: "时间线",
    purpose: "查看当前工程最近的文件式备份，并恢复到某个历史时间点。",
    usage: "点击后会展开时间线面板，备份按新到旧排列。选择记录后需要二次确认才会覆盖当前工程。",
    effect: "备份保存在 workspace 的 backup-timeline 文件夹内，最多保留当前工程最近 10 条记录，不进入卡带或模型配置。",
  },
  "toolbar.autoArrange": {
    title: "整理画布",
    purpose: "把剧情节点按自上而下的推进顺序排开，减少交叉和重叠。",
    usage: "整理整个画布：普通后续垂直向下，分支后续在下一层同层并列展开。",
    effect: "只修改节点卡片位置，不会改写剧情内容、命令、角色、变量或连线关系。",
  },
  "timeline.refresh": {
    title: "刷新时间线",
    purpose: "重新读取 backup-timeline 文件夹里的当前工程备份。",
    usage: "如果你刚刚保存工程，或手动整理过备份文件夹，可以点击刷新。",
    effect: "只刷新列表显示，不会创建、删除或恢复工程。",
  },
  "timeline.entry": {
    title: "时间线备份",
    purpose: "查看并选择一个历史工程备份，准备把当前工程恢复到这个时间点。",
    usage: "点击备份记录后会先打开确认窗口；请核对标题、时间、节点数和连线数。",
    effect: "仅选择备份本身不会立即覆盖工程，确认恢复后才会替换当前画布与工程状态。",
  },
  "timeline.restoreCancel": {
    title: "取消恢复",
    purpose: "关闭恢复确认窗口，保留当前工程不变。",
    usage: "误点备份记录或还没有确认要回滚时点击。",
    effect: "只关闭弹窗，不会读取备份、不写入工程，也不会删除时间线文件。",
  },
  "timeline.restoreConfirm": {
    title: "恢复备份",
    purpose: "把当前工程恢复到选中的时间线备份。",
    usage: "确认当前工程可以被覆盖后再点击；建议先保存当前工程或确认已有最新备份。",
    effect: "会用备份内容替换当前项目画布和工程数据，这是覆盖性操作，但不会删除其他备份记录。",
  },
  "package.platform": {
    title: "目标平台",
    purpose: "选择独立软件包或固定容器工程的构建平台。",
    usage: "左侧发布形式保持为“打包独立软件包”，这里单独切换 Windows 或 Android。切到 Android 后会展开 APK 环境和构建区。",
    effect: "只影响本次打包目标，不会重置发布形式，也不会关闭发布弹层。",
  },
  "settings.runtimeVisual.clear": {
    title: "清空游戏内视觉资源",
    purpose: "移除卡带封面、首页开屏图、设置区图片、设置入口图片等玩家端视觉引用。",
    usage: "需要回到默认 GameCLI 外观时点击。素材库中的原始素材不会被删除。",
    effect: "会清空项目 packageAppearance；后续导出的 manifest.shell 不再写入这些图片字段。",
  },
  "settings.runtimeVisual.cover": {
    title: "卡带封面",
    purpose: "设置卡带库和发布元数据中展示的封面图。",
    usage: "选择背景图、角色图像或界面素材。例：cover_school_gate.png 可作为卡带封面。",
    effect: "导出后写入 manifest.cover，并作为固定容器或卡带库的封面引用。",
  },
  "settings.runtimeVisual.homeSplash": {
    title: "首页开屏图",
    purpose: "设置玩家端标题页或主菜单背景图。",
    usage: "选择背景图或界面素材，建议使用横向 16:9 图片。例：title_evening_sky.png 用作标题页背景。",
    effect: "导出后写入 manifest.shell.background，GameCLI 主菜单会读取并铺满首屏。",
  },
  "settings.runtimeVisual.homeSplashFit": {
    title: "首页背景显示模式",
    purpose: "控制玩家端标题页或主菜单背景图的填充方式。",
    usage: "强制铺满适合希望所有设备都铺满的项目；完整显示适合不能裁切的图；裁切铺满适合保持比例的视觉主图。",
    effect: "导出后写入 manifest.shell.background_fit；旧项目或空值按强制铺满处理。",
  },
  "settings.runtimeVisual.icon": {
    title: "卡带图标",
    purpose: "设置主菜单和卡带信息里使用的小图标。",
    usage: "选择界面素材或角色图像，建议使用清晰正方形图。例：alice_icon.png 用作卡带图标。",
    effect: "导出后写入 manifest.shell.icon；旧卡带不配置时会继续使用封面或默认图标。",
  },
  "settings.runtimeVisual.standaloneIcon": {
    title: "单软件包图标",
    purpose: "设置独立 Windows 安装包或 Android APK 使用的应用图标。",
    usage: "选择清晰的正方形图片素材；未设置时会依次使用卡带图标、卡带封面、默认 AgentVN Player 图标。",
    effect: "只影响独立软件包构建时的应用图标，不写入 .vncart manifest，也不会改变正式安装后的应用名称。",
  },
  "settings.runtimeVisual.settingsPanel": {
    title: "设置区图片",
    purpose: "设置玩家端设置页主体面板的背景图。",
    usage: "选择背景图或界面素材。例：settings_panel.png 用作玩家端设置页面板背景。",
    effect: "导出后写入 manifest.shell.settings_panel_background，并被 GameCLI 设置页读取。",
  },
  "settings.runtimeVisual.settingsPanelFit": {
    title: "设置区背景显示模式",
    purpose: "控制玩家端设置页面板背景图的填充方式。",
    usage: "强制铺满会覆盖整个设置面板；完整显示可能留边；裁切铺满会保持比例并裁掉边缘。",
    effect: "导出后写入 manifest.shell.settings_panel_background_fit；旧项目或空值按强制铺满处理。",
  },
  "settings.runtimeVisual.settingsEntry": {
    title: "设置入口图片",
    purpose: "设置主菜单“设置”按钮旁的自定义入口图。",
    usage: "选择界面素材或角色图像，建议使用可在小尺寸下识别的图。例：settings_badge.png 用在设置入口旁。",
    effect: "导出后写入玩家端设置入口图片；未设置时保留默认设置图标。",
  },
  "package.runtimeVisual.homeSplash": {
    title: "发布首页开屏图",
    purpose: "在发布弹层中快速调整本次玩家端首页背景。",
    usage: "选择素材后会同步写入项目设置，与工具/设置中的游戏内视觉资源保持一致。",
    effect: "会影响后续 .vncart、Windows 独立包和 Android APK 的 manifest.shell.background。",
  },
  "package.runtimeVisual.homeSplashFit": {
    title: "发布首页背景显示模式",
    purpose: "在发布前确认首页或主菜单背景图的填充方式。",
    usage: "强制铺满、完整显示、裁切铺满三种模式会同步保存到项目设置。",
    effect: "会影响后续 .vncart、Windows 独立包和 Android APK 的 manifest.shell.background_fit。",
  },
  "package.runtimeVisual.standaloneIcon": {
    title: "发布单软件包图标",
    purpose: "在打包独立软件包前确认安装包和应用图标。",
    usage: "选择后会同步保存到项目设置；留空时会回退到卡带图标，再回退到卡带封面。",
    effect: "Windows 打包时会临时生成 Tauri 图标并恢复源码默认图标；输出目录只保留安装包，不额外导出图标文件。",
  },
  "package.runtimeVisual.settingsPanel": {
    title: "发布设置区图片",
    purpose: "在发布前确认玩家端设置页背景。",
    usage: "适合打包前快速替换或检查设置页视觉资源。",
    effect: "会写入 manifest.shell.settings_panel_background，并随卡带打入独立软件包。",
  },
  "package.runtimeVisual.settingsPanelFit": {
    title: "发布设置区背景显示模式",
    purpose: "在发布前确认设置页面板背景图的填充方式。",
    usage: "强制铺满、完整显示、裁切铺满三种模式会同步保存到项目设置。",
    effect: "会写入 manifest.shell.settings_panel_background_fit，并随卡带打入独立软件包。",
  },
  "package.runtimeVisual.settingsEntry": {
    title: "发布设置入口图片",
    purpose: "在发布前确认主菜单设置按钮的小图。",
    usage: "选择一个小尺寸识别度高的 UI 图或角色头像。",
    effect: "会写入 manifest.shell.settings_entry_image；GameCLI 主菜单有图时显示图片，无图时显示默认图标。",
  },
  "command.dialog.style.restoreInherit": {
    title: "恢复继承",
    purpose: "让当前对白不再使用本句手动外观，重新继承角色默认或玩家端 UI skin。",
    usage: "某句不需要特殊底图或主题色时点击。",
    effect: "只改当前命令的 dialog_style_mode，不会删除角色默认样式。",
  },
  "command.dialog.style.background": {
    title: "对白框底图",
    purpose: "为当前对白选择 UI 类型底图。",
    usage: "选择后当前对白会自动切换为本句手动覆盖。",
    effect: "导出后写入 DialogCommand.dialog_style.background_asset_id；运行端优先级高于角色默认。",
  },
  "command.dialog.style.backgroundFit": {
    title: "对白框底图显示模式",
    purpose: "控制对白框底图是否拉伸、完整留边或裁切铺满。",
    usage: "该设置既可以用于本句手动覆盖，也会在“设为角色默认”后被该角色的继承对白使用。",
    effect: "导出后写入 DialogVisualStyle.background_fit，并由 GameCLI 转换为对应的 background-size。",
  },
  "command.narration.style.background": {
    title: "旁白框底图",
    purpose: "为当前旁白选择 UI 类型底图。",
    usage: "选择后仅覆盖当前这句旁白的对话框背景；清空后回到玩家端 UI skin。",
    effect: "导出后写入 NarrationCommand.dialog_style.background_asset_id，并由 GameCLI 作为旁白框底图渲染。",
  },
  "command.narration.style.backgroundFit": {
    title: "旁白框底图显示模式",
    purpose: "控制旁白框底图是否保持比例、留边或裁切。",
    usage: "强制铺满会拉伸；完整显示会保持比例并可能留边；裁切铺满会保持比例并裁掉边缘。",
    effect: "导出后写入 NarrationCommand.dialog_style.background_fit，并由 GameCLI 转换为对应的 background-size。",
  },
  "command.narration.style.applyAll": {
    title: "应用旁白外观到全部旁白",
    purpose: "把当前旁白的底图、显示模式和文字样式批量应用到项目中的全部旁白。",
    usage: "先完成当前旁白的外观设置，再点击此按钮；旁白文本和单独字体素材不会被修改。",
    effect: "所有场景中的旁白都会改为 manual 样式，并进入编辑器撤销历史。",
  },
  "command.dialog.style.color": {
    title: "对白主题色",
    purpose: "打开自定义调色盘，为当前对白选择强调色。",
    usage: "可用色板快速选择，也可输入 HEX。应用后当前句成为手动覆盖。",
    effect: "运行端会把主题色应用到对白框边缘、姓名牌和继续提示。",
  },
  "command.dialog.style.manual": {
    title: "本句单独覆盖",
    purpose: "把当前继承效果固定为本句专属外观。",
    usage: "当这句对白需要不同底图或主题色时点击。",
    effect: "后续一键保存角色默认不会覆盖这句手动设置。",
  },
  "command.dialog.style.saveDefault": {
    title: "设为角色默认",
    purpose: "把当前对白外观保存为该角色后续对白的默认样式。",
    usage: "先设置底图或主题色，再点击保存为角色默认。",
    effect: "只写入 ProjectSettings.characterDialogStyles；已有 manual 单句不会被批量改写。",
  },
  "command.dialog.style.clearDefault": {
    title: "清除角色默认",
    purpose: "移除当前角色的默认对白外观。",
    usage: "想回到玩家端 UI skin 默认对白样式时使用。",
    effect: "只清除角色默认记录，不影响已设置为 manual 的单句对白。",
  },
  "colorPicker.close": {
    title: "关闭调色盘",
    purpose: "关闭颜色选择弹窗且不应用未保存的颜色。",
  },
  "assetPicker.close": {
    title: "关闭素材选择",
    purpose: "收起当前素材选择弹窗，保留字段里已经选中的素材。",
    usage: "确认不再浏览素材库，或需要回到当前编辑表单时点击。",
    effect: "只关闭弹窗，不会导入、删除或替换任何素材。",
  },
  "colorPicker.input": {
    title: "HEX 颜色值",
    purpose: "手动输入六位十六进制颜色。",
    usage: "格式示例：#d58a72。",
  },
  "colorPicker.swatch": {
    title: "常用色板",
    purpose: "从预设色块中快速选择对白主题色。",
  },
  "colorPicker.clear": {
    title: "清除颜色",
    purpose: "移除当前主题色，让对白继续使用继承或默认颜色。",
  },
  "colorPicker.cancel": {
    title: "取消调色",
    purpose: "关闭调色盘，不写入当前草稿颜色。",
  },
  "colorPicker.apply": {
    title: "应用颜色",
    purpose: "把当前调色盘颜色写入对白外观。",
    effect: "会让当前对白成为手动覆盖，除非你再点击恢复继承。",
  },
} as const satisfies Record<string, HoverHelpEntry>;

export type HoverHelpKey = keyof typeof hoverHelpCatalog;

export const titleReplacements: Array<[RegExp, string]> = [
  [/player shell/i, "玩家客户端"],
];

export const hoverHelpPatterns: Array<[RegExp, HoverHelpKey]> = [
  [/项目设置|project settings/i, "advanced.tab.settings"],
  [/客户端布局|布局位置|runtime layout/i, "advanced.tab.layout"],
  [/客户端主题|主题配色|滑杆配色|滑杆颜色|GameCLI theme|runtime theme/i, "advanced.tab.theme"],
  [/预览|preview/i, "advanced.tab.preview"],
  [/项目名称|title/i, "settings.projectTitle"],
  [/作者|author/i, "settings.author"],
  [/模型|default model/i, "provider.defaultModel"],
  [/系统提示词|system prompt/i, "provider.systemPrompt"],
  [/发布形式|package mode/i, "package.mode"],
];

export function formatHoverHelp(entry: HoverHelpEntry): string {
  const detailedSections = [
    entry.summary,
    entry.whenToUse,
    entry.howToUse,
    entry.wiring,
    entry.bestPractices,
    entry.pitfalls,
    entry.example,
  ].filter(Boolean);

  if (detailedSections.length > 0) {
    return detailedSections.join("\n\n").trim();
  }

  return `${entry.purpose ?? ""} ${entry.usage ?? ""} ${entry.effect ?? ""}`.replace(/\s+/g, " ").trim();
}

export function getHoverHelpEntry(key: string | undefined | null): HoverHelpEntry | undefined {
  if (!key) return undefined;
  return hoverHelpCatalog[key as HoverHelpKey];
}

export function getPatternHelpEntry(title: string): HoverHelpEntry | undefined {
  const matched = hoverHelpPatterns.find(([pattern]) => pattern.test(title));
  return matched ? hoverHelpCatalog[matched[1]] : undefined;
}
