import type { AnimationPreset } from "./types";

export const builtInAnimationPresets: AnimationPreset[] = [
  {
    preset_id: "sprite_fade_in",
    name: "立绘淡入",
    description: "角色柔和出现，适合常规入场。",
    target_type: "sprite",
    duration_ms: 500,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 0 },
      { offset: 1, opacity: 1 },
    ],
  },
  {
    preset_id: "sprite_fade_out",
    name: "立绘淡出",
    description: "角色柔和退场，适合场景收束。",
    target_type: "sprite",
    duration_ms: 420,
    easing: "ease-in",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 1 },
      { offset: 1, opacity: 0 },
    ],
  },
  {
    preset_id: "sprite_slide_in_left",
    name: "左侧滑入",
    description: "角色从画面左侧滑入。",
    target_type: "sprite",
    duration_ms: 560,
    easing: "cubic-bezier(.2,.8,.2,1)",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 0, x: -120 },
      { offset: 1, opacity: 1, x: 0 },
    ],
  },
  {
    preset_id: "sprite_slide_in_right",
    name: "右侧滑入",
    description: "角色从画面右侧滑入。",
    target_type: "sprite",
    duration_ms: 560,
    easing: "cubic-bezier(.2,.8,.2,1)",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 0, x: 120 },
      { offset: 1, opacity: 1, x: 0 },
    ],
  },
  {
    preset_id: "sprite_slide_out_left",
    name: "向左滑出",
    description: "角色向左侧快速离场。",
    target_type: "sprite",
    duration_ms: 460,
    easing: "ease-in",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 1, x: 0 },
      { offset: 1, opacity: 0, x: -140 },
    ],
  },
  {
    preset_id: "sprite_slide_out_right",
    name: "向右滑出",
    description: "角色向右侧快速离场。",
    target_type: "sprite",
    duration_ms: 460,
    easing: "ease-in",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 1, x: 0 },
      { offset: 1, opacity: 0, x: 140 },
    ],
  },
  {
    preset_id: "sprite_pop",
    name: "轻微放大强调",
    description: "适合台词强调或短促情绪起伏。",
    target_type: "sprite",
    duration_ms: 420,
    easing: "cubic-bezier(.18,.88,.22,1.16)",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1, opacity: 1 },
      { offset: 0.45, scale: 1.08, opacity: 1 },
      { offset: 1, scale: 1, opacity: 1 },
    ],
  },
  {
    preset_id: "sprite_focus",
    name: "心理聚焦",
    description: "压暗背景和陪衬角色，轻微放大目标角色，适合心理活动与内心独白。",
    target_type: "sprite",
    duration_ms: 1400,
    easing: "ease-in-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1 },
      { offset: 0.18, scale: 1.055 },
      { offset: 0.76, scale: 1.055 },
      { offset: 1, scale: 1 },
    ],
  },
  {
    preset_id: "sprite_shake",
    name: "立绘抖动",
    description: "适合惊讶、愤怒或受击反应。",
    target_type: "sprite",
    duration_ms: 360,
    easing: "linear",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, x: 0 },
      { offset: 0.25, x: -10 },
      { offset: 0.5, x: 9 },
      { offset: 0.75, x: -5 },
      { offset: 1, x: 0 },
    ],
  },
  {
    preset_id: "sprite_heartbeat",
    name: "心跳缩放",
    description: "适合暧昧、紧张或情绪持续波动。",
    target_type: "sprite",
    duration_ms: 780,
    easing: "ease-in-out",
    loop: true,
    direction: "alternate",
    keyframes: [
      { offset: 0, scale: 1 },
      { offset: 0.45, scale: 1.06 },
      { offset: 1, scale: 1 },
    ],
  },
  {
    preset_id: "background_fade",
    name: "背景淡入",
    description: "适合平稳切换场景背景。",
    target_type: "background",
    duration_ms: 620,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, opacity: 0 },
      { offset: 1, opacity: 1 },
    ],
  },
  {
    preset_id: "background_blur_in",
    name: "背景清晰出现",
    description: "从模糊过渡到清晰，适合回忆或聚焦。",
    target_type: "background",
    duration_ms: 620,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, blur: 12, opacity: 0 },
      { offset: 1, blur: 0, opacity: 1 },
    ],
  },
  {
    preset_id: "background_blur_out",
    name: "背景模糊退场",
    description: "适合回忆结束或失焦切换。",
    target_type: "background",
    duration_ms: 520,
    easing: "ease-in",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, blur: 0, opacity: 1 },
      { offset: 1, blur: 14, opacity: 0 },
    ],
  },
  {
    preset_id: "background_push_in",
    name: "背景轻微推进",
    description: "让场景更有空间感，适合转入重点氛围。",
    target_type: "background",
    duration_ms: 860,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1.04, opacity: 0.92 },
      { offset: 1, scale: 1, opacity: 1 },
    ],
  },
  {
    preset_id: "camera_zoom_in",
    name: "镜头推进",
    description: "适合拉近情绪焦点或强调表情。",
    target_type: "camera",
    duration_ms: 900,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1 },
      { offset: 1, scale: 1.08 },
    ],
  },
  {
    preset_id: "camera_zoom_out",
    name: "镜头拉远",
    description: "适合收束气氛或扩大环境感。",
    target_type: "camera",
    duration_ms: 820,
    easing: "ease-out",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1.06 },
      { offset: 1, scale: 1 },
    ],
  },
  {
    preset_id: "camera_shake",
    name: "镜头震动",
    description: "适合爆点、碰撞、惊吓或冲击。",
    target_type: "camera",
    duration_ms: 420,
    easing: "linear",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, x: 0 },
      { offset: 0.3, x: -18 },
      { offset: 0.6, x: 14 },
      { offset: 1, x: 0 },
    ],
  },
  {
    preset_id: "camera_impact",
    name: "瞬时冲击",
    description: "快速缩放并轻震，适合重要句点或打击感。",
    target_type: "camera",
    duration_ms: 320,
    easing: "cubic-bezier(.2,.9,.2,1)",
    loop: false,
    direction: "normal",
    keyframes: [
      { offset: 0, scale: 1, x: 0 },
      { offset: 0.35, scale: 1.06, x: -10 },
      { offset: 0.7, scale: 1.02, x: 7 },
      { offset: 1, scale: 1, x: 0 },
    ],
  },
];
